-- Run once on claims_poc (manual setup)

CREATE TABLE IF NOT EXISTS acuity_watchlist (
  ID          INT AUTO_INCREMENT PRIMARY KEY,
  FULL_NAME   VARCHAR(200) NOT NULL,
  DOB         DATE NULL,
  COUNTRY     VARCHAR(100) NULL
);

ALTER TABLE claims
  ADD COLUMN IF NOT EXISTS CLAIMANT_ACUITY_DECISION VARCHAR(20) NULL DEFAULT 'NOT FLAGGED',
  ADD COLUMN IF NOT EXISTS PAYEE_ACUITY_DECISION    VARCHAR(20) NULL DEFAULT 'NOT FLAGGED',
  ADD COLUMN IF NOT EXISTS FINAL_ACUITY_DECISION    VARCHAR(20) NULL DEFAULT 'NOT FLAGGED';

-- Sample watchlist (skip if already inserted)
INSERT INTO acuity_watchlist (FULL_NAME, DOB, COUNTRY) VALUES
('Atharva', '1990-05-15', 'Monaco'),
('Mohit',   '1985-01-01', 'Maldives'),
('Om',      '1992-03-20', 'Malta');
