USE claims_poc;

CREATE TABLE IF NOT EXISTS acuity_watchlist (
  ID          INT AUTO_INCREMENT PRIMARY KEY,
  FULL_NAME   VARCHAR(200) NOT NULL,
  DOB         DATE NULL,
  COUNTRY     VARCHAR(100) NULL
);

SET @db = DATABASE();

SET @col1 = (
  SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'claims' AND COLUMN_NAME = 'CLAIMANT_ACUITY_DECISION'
);
SET @sql1 = IF(@col1 = 0,
  'ALTER TABLE claims ADD COLUMN CLAIMANT_ACUITY_DECISION VARCHAR(20) NULL DEFAULT ''NOT FLAGGED''',
  'SELECT ''CLAIMANT_ACUITY_DECISION exists'' AS info');
PREPARE stmt1 FROM @sql1; EXECUTE stmt1; DEALLOCATE PREPARE stmt1;

SET @col2 = (
  SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'claims' AND COLUMN_NAME = 'PAYEE_ACUITY_DECISION'
);
SET @sql2 = IF(@col2 = 0,
  'ALTER TABLE claims ADD COLUMN PAYEE_ACUITY_DECISION VARCHAR(20) NULL DEFAULT ''NOT FLAGGED''',
  'SELECT ''PAYEE_ACUITY_DECISION exists'' AS info');
PREPARE stmt2 FROM @sql2; EXECUTE stmt2; DEALLOCATE PREPARE stmt2;

SET @col3 = (
  SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'claims' AND COLUMN_NAME = 'FINAL_ACUITY_DECISION'
);
SET @sql3 = IF(@col3 = 0,
  'ALTER TABLE claims ADD COLUMN FINAL_ACUITY_DECISION VARCHAR(20) NULL DEFAULT ''NOT FLAGGED''',
  'SELECT ''FINAL_ACUITY_DECISION exists'' AS info');
PREPARE stmt3 FROM @sql3; EXECUTE stmt3; DEALLOCATE PREPARE stmt3;

INSERT INTO acuity_watchlist (FULL_NAME, DOB, COUNTRY)
SELECT 'Atharva', '1990-05-15', 'Monaco'
WHERE NOT EXISTS (SELECT 1 FROM acuity_watchlist WHERE FULL_NAME = 'Atharva' AND DOB = '1990-05-15');

INSERT INTO acuity_watchlist (FULL_NAME, DOB, COUNTRY)
SELECT 'Mohit', '1985-01-01', 'Maldives'
WHERE NOT EXISTS (SELECT 1 FROM acuity_watchlist WHERE FULL_NAME = 'Mohit' AND DOB = '1985-01-01');

INSERT INTO acuity_watchlist (FULL_NAME, DOB, COUNTRY)
SELECT 'Om', '1992-03-20', 'Malta'
WHERE NOT EXISTS (SELECT 1 FROM acuity_watchlist WHERE FULL_NAME = 'Om' AND DOB = '1992-03-20');

SELECT 'acuity_watchlist' AS tbl, COUNT(*) AS row_count FROM acuity_watchlist;
SHOW COLUMNS FROM claims LIKE '%ACUITY%';
