-- =============================================================================
-- migration: 0001_baseline_schema
-- description: Baseline schema v1 — snapshot of the claims_poc database as it
--              existed when the migration framework was introduced.
--
--   * Captured from the live schema via SHOW CREATE TABLE (100 tables).
--   * All CREATE statements use IF NOT EXISTS, so applying this to an EXISTING
--     (brownfield) DEV/UAT/PROD database is a no-op that simply records the
--     baseline in schema_migrations. On a fresh/empty database it builds the
--     full schema from scratch.
--   * Volatile AUTO_INCREMENT counters were stripped so the baseline is stable
--     across environments.
--   * Excluded 7 backup_* tables (ad-hoc data backups, not part of the schema):
--       backup_caps_add_assessor_pool_cases, backup_caps_add_contract_details, backup_caps_add_decision, backup_caps_add_details, backup_caps_add_findings, backup_caps_add_life_assured_details, backup_caps_add_raw_data
--   * This baseline is a faithful MySQL dump. A future Oracle target needs an
--     Oracle-flavoured baseline (see src/db/dialects/oracle.js); everything
--     from 0002 onward should be authored in neutral SQL.
--
-- Regenerate note: do NOT edit this file after it has been applied anywhere —
-- add a new numbered migration instead. (The engine warns on checksum drift.)
-- =============================================================================

-- @UP  ------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `acuity_watchlist` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FULL_NAME` varchar(200) NOT NULL,
  `DOB` date DEFAULT NULL,
  `COUNTRY` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `agent_repudiation_history` (
  `POLICY_NO` varchar(200) DEFAULT NULL,
  `POLICY_STATUS` varchar(200) DEFAULT NULL,
  `FLAG` varchar(200) DEFAULT NULL,
  `SEQ_NO` varchar(200) NOT NULL,
  `CLAIM_ID` varchar(200) NOT NULL,
  `AGENT_TYPE` varchar(200) DEFAULT NULL,
  `AGENT_CODE` varchar(200) DEFAULT NULL,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `CREATED_ON` datetime DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `agentdetails` (
  `id` int NOT NULL AUTO_INCREMENT,
  `policyNumber` varchar(255) NOT NULL,
  `AgentType` varchar(255) DEFAULT NULL,
  `AgentTypeDesc` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `agentrepudiation` (
  `id` int NOT NULL AUTO_INCREMENT,
  `POLICY_NO` varchar(100) NOT NULL,
  `AGENT_CODE` varchar(100) DEFAULT NULL,
  `AGENT_TYPE` varchar(50) DEFAULT NULL,
  `POLICY_STATUS` varchar(50) DEFAULT NULL,
  `FLAG` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `attachment` (
  `DocID` int NOT NULL AUTO_INCREMENT,
  `inward_id` varchar(20) NOT NULL,
  `document_name` varchar(200) NOT NULL,
  `document_type` varchar(200) NOT NULL,
  `created_on` varchar(45) NOT NULL,
  `ALF_DocID` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`DocID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_activity_trail` (
  `seq_no` int NOT NULL AUTO_INCREMENT,
  `case_id` int NOT NULL,
  `policy_number` varchar(20) DEFAULT NULL,
  `case_status` varchar(50) DEFAULT NULL,
  `user_role` varchar(20) DEFAULT NULL,
  `user_id` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`seq_no`,`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_assessor_pool_cases` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `CASE_ID` bigint NOT NULL,
  `APPLICATION_NO` varchar(50) DEFAULT NULL,
  `POLICY_NO` varchar(50) DEFAULT NULL,
  `KSN` varchar(50) DEFAULT NULL,
  `SOURCE` varchar(50) DEFAULT NULL,
  `REFERRAL_DATE` date DEFAULT NULL,
  `TRIGGER_DATE` date DEFAULT NULL,
  `CASE_STATUS` varchar(50) DEFAULT NULL,
  `IS_EXCLUDED` char(1) DEFAULT NULL,
  `EXCLUSION_TYPE` varchar(100) DEFAULT NULL,
  `STATUS` varchar(50) DEFAULT NULL,
  `IRSS_STATUS` varchar(50) DEFAULT NULL,
  `SCH_AGING` int DEFAULT NULL,
  `PRODUCT_CODE` varchar(20) DEFAULT NULL,
  `POLICY_STATUS` varchar(50) DEFAULT NULL,
  `BASE_SA` decimal(15,2) DEFAULT NULL,
  `CITY` varchar(50) DEFAULT NULL,
  `STATE` varchar(50) DEFAULT NULL,
  `PINCODE` varchar(10) DEFAULT NULL,
  `BATCH_ID` bigint DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CASE_ID` (`CASE_ID`,`BATCH_ID`),
  CONSTRAINT `caps_add_assessor_pool_cases_chk_1` CHECK ((`IS_EXCLUDED` in (_utf8mb4'Y',_utf8mb4'N')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_contract_details` (
  `contract_id` int NOT NULL AUTO_INCREMENT,
  `case_id` int DEFAULT NULL,
  `app_no` varchar(20) DEFAULT NULL,
  `policy_no` varchar(20) DEFAULT NULL,
  `product_name` varchar(50) DEFAULT NULL,
  `product_code` varchar(20) DEFAULT NULL,
  `policy_duration` varchar(20) DEFAULT NULL,
  `rcd` date DEFAULT NULL,
  `pad` varchar(30) DEFAULT NULL,
  `fid` varchar(30) DEFAULT NULL,
  `adbr_sa` varchar(20) DEFAULT NULL,
  `ci_sa` varchar(20) DEFAULT NULL,
  `premium_frequency` varchar(20) DEFAULT NULL,
  `premium_amount` varchar(20) DEFAULT NULL,
  `premiums_paid` varchar(20) DEFAULT NULL,
  `annual_premium` varchar(20) DEFAULT NULL,
  `channel_9` varchar(20) DEFAULT NULL,
  `channel_4` varchar(20) DEFAULT NULL,
  `agent_category` varchar(20) DEFAULT NULL,
  `agent_fsc_code` varchar(20) DEFAULT NULL,
  `agent_fsc_name` varchar(200) DEFAULT NULL,
  `um_sm_code` varchar(20) DEFAULT NULL,
  `um_sm_name` varchar(20) DEFAULT NULL,
  `agent_active_not_active` varchar(20) DEFAULT NULL,
  `uw_decision` varchar(20) DEFAULT NULL,
  `biu_output` varchar(20) DEFAULT NULL,
  `nb_risk_done` varchar(20) DEFAULT NULL,
  `medicals_done` varchar(20) DEFAULT NULL,
  `pvv_done` varchar(20) DEFAULT NULL,
  `experian_credit_score` varchar(20) DEFAULT NULL,
  `policy_status` varchar(20) DEFAULT NULL,
  `agent_stat_code` varchar(20) DEFAULT NULL,
  `base_sa` int DEFAULT NULL,
  PRIMARY KEY (`contract_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_decision` (
  `decision_id` int NOT NULL AUTO_INCREMENT,
  `case_id` int DEFAULT NULL,
  `policy_number` varchar(20) DEFAULT NULL,
  `rule` varchar(50) DEFAULT NULL,
  `final_decision` varchar(50) DEFAULT NULL,
  `sddr_received` varchar(20) DEFAULT NULL,
  `sddr_date` date DEFAULT NULL,
  `sddr_decision` varchar(20) DEFAULT NULL,
  `scn_received` varchar(20) DEFAULT NULL,
  `scn_date` date DEFAULT NULL,
  `scn_decision` varchar(20) DEFAULT NULL,
  `scn_aging` int DEFAULT NULL,
  `scn_sent` varchar(20) DEFAULT NULL,
  `add_case_remarks` text,
  `created_by` varchar(20) DEFAULT NULL,
  `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_by` varchar(20) DEFAULT NULL,
  `modified_on` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`decision_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_decision_history` (
  `history_id` int NOT NULL AUTO_INCREMENT,
  `case_id` int DEFAULT NULL,
  `policy_number` varchar(20) DEFAULT NULL,
  `rule` varchar(50) DEFAULT NULL,
  `final_decision` varchar(20) DEFAULT NULL,
  `created_by` varchar(20) DEFAULT NULL,
  `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `sddr_received` varchar(20) DEFAULT NULL,
  `sddr_date` date DEFAULT NULL,
  `sddr_decision` varchar(20) DEFAULT NULL,
  `scn_received` varchar(20) DEFAULT NULL,
  `scn_date` date DEFAULT NULL,
  `scn_decision` varchar(20) DEFAULT NULL,
  `scn_aging` int DEFAULT NULL,
  `scn_sent` varchar(20) DEFAULT NULL,
  `add_case_remarks` text,
  PRIMARY KEY (`history_id`),
  KEY `fk_case_id` (`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_decision_master` (
  `id` int NOT NULL AUTO_INCREMENT,
  `findings` varchar(100) DEFAULT NULL,
  `remarks` varchar(100) DEFAULT NULL,
  `rule` varchar(20) DEFAULT NULL,
  `decision` varchar(20) DEFAULT NULL,
  `severity` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_details` (
  `case_id` int NOT NULL AUTO_INCREMENT,
  `policy_number` varchar(20) DEFAULT NULL,
  `krn` varchar(20) DEFAULT NULL,
  `source` varchar(20) DEFAULT NULL,
  `referral_date` timestamp NULL DEFAULT NULL,
  `initiation_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `case_status` varchar(100) DEFAULT NULL,
  `exclusion_type_rule` varchar(50) DEFAULT NULL,
  `initiation_remarks` varchar(500) DEFAULT NULL,
  `created_by` varchar(20) DEFAULT NULL,
  `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_by` varchar(20) DEFAULT NULL,
  `modified_on` timestamp NULL DEFAULT NULL,
  `to_be_refer` varchar(20) DEFAULT '0',
  `iris_status` varchar(100) DEFAULT NULL,
  `assigned_to` varchar(50) DEFAULT NULL,
  `assigned_by` varchar(50) DEFAULT NULL,
  `refresh_la_flag` int DEFAULT NULL,
  PRIMARY KEY (`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_details_history` (
  `history_id` int NOT NULL AUTO_INCREMENT,
  `case_id` int DEFAULT NULL,
  `policy_number` varchar(20) DEFAULT NULL,
  `krn` varchar(20) DEFAULT NULL,
  `source` varchar(20) DEFAULT NULL,
  `referral_date` timestamp NULL DEFAULT NULL,
  `initiation_date` timestamp NULL DEFAULT NULL,
  `case_status` varchar(100) DEFAULT NULL,
  `exclusion_type_rule` varchar(50) DEFAULT NULL,
  `initiation_remarks` varchar(20) DEFAULT NULL,
  `created_by` varchar(20) DEFAULT NULL,
  `created_on` timestamp NULL DEFAULT NULL,
  `to_be_refer` int DEFAULT NULL,
  `iris_status` varchar(100) DEFAULT NULL,
  `assigned_to` varchar(20) DEFAULT NULL,
  `assigned_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`history_id`),
  KEY `fk_caps_detailsHistory_case_id` (`case_id`),
  CONSTRAINT `fk_caps_detailsHistory_case_id` FOREIGN KEY (`case_id`) REFERENCES `caps_add_details` (`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_exclusion_master` (
  `exclusion_type` varchar(100) DEFAULT NULL,
  `exclusion_value` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_findings` (
  `seq_no` int NOT NULL AUTO_INCREMENT,
  `case_id` int DEFAULT NULL,
  `findings` varchar(100) DEFAULT NULL,
  `remarks` varchar(100) DEFAULT NULL,
  `rule` varchar(20) DEFAULT NULL,
  `decision` varchar(20) DEFAULT NULL,
  `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `modified_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modified_by` varchar(50) DEFAULT NULL,
  `ailment_name` varchar(100) DEFAULT NULL,
  `ailment_type` varchar(50) DEFAULT NULL,
  `medical_records` varchar(50) DEFAULT NULL,
  `type_of_evidence` varchar(50) DEFAULT NULL,
  `severity` int DEFAULT NULL,
  PRIMARY KEY (`seq_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_iib_enquiry` (
  `seq_no` int NOT NULL AUTO_INCREMENT,
  `case_id` int NOT NULL,
  `transactionid` varchar(200) DEFAULT NULL,
  `policy_number` varchar(15) DEFAULT NULL,
  `proposal_number` varchar(15) DEFAULT NULL,
  `query_type` varchar(1) DEFAULT NULL,
  `dop_doc` date DEFAULT NULL,
  `sum_assured` int DEFAULT NULL,
  `la_first_name` varchar(75) DEFAULT NULL,
  `la_middle_name` varchar(25) DEFAULT NULL,
  `la_last_name` varchar(75) DEFAULT NULL,
  `la_dob` date DEFAULT NULL,
  `la_gender` varchar(1) DEFAULT NULL,
  `la_current_address` varchar(500) DEFAULT NULL,
  `la_permanent_address` varchar(500) DEFAULT NULL,
  `la_pin_code` int DEFAULT NULL,
  `la_pan` varchar(10) DEFAULT NULL,
  `la_aadhar` bigint DEFAULT NULL,
  `la_ckyc` bigint DEFAULT NULL,
  `la_passport` varchar(8) DEFAULT NULL,
  `la_dl` varchar(20) DEFAULT NULL,
  `la_voter_id` varchar(16) DEFAULT NULL,
  `la_phone_number_1` varchar(20) DEFAULT NULL,
  `la_phone_number_2` bigint DEFAULT NULL,
  `la_email_1` varchar(50) DEFAULT NULL,
  `la_email_2` varchar(50) DEFAULT NULL,
  `date_of_death` date DEFAULT NULL,
  `status` varchar(100) DEFAULT NULL,
  `remark` text,
  `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `company_number` varchar(2000) DEFAULT NULL,
  `product_type` varchar(2000) DEFAULT NULL,
  `product_uin` varchar(2000) DEFAULT NULL,
  `annual_income` varchar(2000) DEFAULT NULL,
  `cause_of_death` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`seq_no`,`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_krn_details` (
  `seq_no` int NOT NULL AUTO_INCREMENT,
  `case_id` int DEFAULT NULL,
  `krn` varchar(20) DEFAULT NULL,
  `policy_number` varchar(20) DEFAULT NULL,
  `referral_date` date DEFAULT NULL,
  `sh_status` varchar(50) DEFAULT NULL,
  `rc_sugg_rcmd` varchar(20) DEFAULT NULL,
  `rc_remarks` varchar(20) DEFAULT NULL,
  `activity_status` varchar(50) DEFAULT NULL,
  `investigation_type` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`seq_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_letter_details` (
  `seq_no` int NOT NULL AUTO_INCREMENT,
  `case_id` int DEFAULT NULL,
  `letter_code` varchar(20) DEFAULT NULL,
  `letter_path` varchar(500) DEFAULT NULL,
  `triggered_by` varchar(20) DEFAULT NULL,
  `triggered_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`seq_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_life_assured_details` (
  `seq_no` int NOT NULL AUTO_INCREMENT,
  `case_id` int NOT NULL,
  `name` varchar(50) DEFAULT NULL,
  `client_id` varchar(20) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `age` varchar(20) DEFAULT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `res_status` varchar(20) DEFAULT NULL,
  `income` varchar(200) DEFAULT NULL,
  `occupation` varchar(200) DEFAULT NULL,
  `education` varchar(200) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `state` varchar(50) DEFAULT NULL,
  `pan_no` varchar(20) DEFAULT NULL,
  `mobile_no` varchar(20) DEFAULT NULL,
  `created_by` varchar(20) DEFAULT NULL,
  `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_by` varchar(20) DEFAULT NULL,
  `modified_on` timestamp NULL DEFAULT NULL,
  `pincode` varchar(20) DEFAULT NULL,
  `flat` varchar(100) DEFAULT NULL,
  `road` varchar(100) DEFAULT NULL,
  `area` varchar(100) DEFAULT NULL,
  `occupation_desc` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`seq_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_raw_data` (
  `seq_id` int NOT NULL AUTO_INCREMENT,
  `policy_number` varchar(20) DEFAULT NULL,
  `source` varchar(20) DEFAULT NULL,
  `referral_date` timestamp NULL DEFAULT NULL,
  `initiation_remarks` varchar(500) DEFAULT NULL,
  `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(20) DEFAULT NULL,
  `modified_on` timestamp NULL DEFAULT NULL,
  `modified_by` varchar(20) DEFAULT NULL,
  `processed_flag` int DEFAULT '0',
  PRIMARY KEY (`seq_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_requirement_master` (
  `findings` varchar(500) DEFAULT NULL,
  `requirement` varchar(500) DEFAULT NULL,
  `comp_code` varchar(50) DEFAULT NULL,
  `severity` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_rider_details` (
  `seq_no` int NOT NULL AUTO_INCREMENT,
  `case_id` int DEFAULT NULL,
  `rider_code` varchar(50) DEFAULT NULL,
  `rider_sa` varchar(50) DEFAULT NULL,
  `rider_status` varchar(20) DEFAULT NULL,
  `rider_cess_date` date DEFAULT NULL,
  `rider_comm_date` date DEFAULT NULL,
  `created_on` timestamp NULL DEFAULT NULL,
  `created_by` varchar(20) DEFAULT NULL,
  `modified_on` timestamp NULL DEFAULT NULL,
  `modified_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`seq_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_sms_details` (
  `seq_no` int NOT NULL AUTO_INCREMENT,
  `case_id` int DEFAULT NULL,
  `sms_campaign_name` varchar(50) DEFAULT NULL,
  `mobile_no` varchar(20) DEFAULT NULL,
  `triggered_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `triggered_by` varchar(20) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `transaction_id` varchar(50) DEFAULT NULL,
  `not_send_reason` varchar(50) DEFAULT NULL,
  `send_flag` int DEFAULT '0',
  PRIMARY KEY (`seq_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_add_sms_master` (
  `seq_id` int NOT NULL AUTO_INCREMENT,
  `campaign_name` varchar(50) DEFAULT NULL,
  `action` varchar(50) DEFAULT NULL,
  `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`seq_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_assessment_qustns_master` (
  `ASSESSMENT_QUES_ID` int DEFAULT NULL,
  `BRE_QUESTION_ID` text,
  `BRE_QUES_DESC` text,
  `STATUS` text,
  `CREATEDON` text,
  `CREATEDBY` text,
  `MODIFIEDON` text,
  `MODIFIEDBY` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_bre_requirement_master` (
  `PORTFOLIO_TYPE` text,
  `TYPE_OF_CLAIM` text,
  `POLICY_STATUS` text,
  `DOCUMENT_NAME` text,
  `OCCUPATION` text,
  `SUM_ASSURED` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_eagle_rule_details` (
  `seq_number` int NOT NULL AUTO_INCREMENT,
  `claim_id` varchar(200) DEFAULT NULL,
  `ruleCode` varchar(100) DEFAULT NULL,
  `user_id` varchar(100) DEFAULT NULL,
  `user_role` varchar(100) DEFAULT NULL,
  `decision` varchar(200) DEFAULT NULL,
  `remark` varchar(200) DEFAULT NULL,
  `result` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`seq_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_event_details` (
  `CAUSE_CATEGORY` varchar(200) DEFAULT NULL,
  `CAUSE_CODE` varchar(200) DEFAULT NULL,
  `CAUSE_DESCRIPTION` varchar(200) DEFAULT NULL,
  `CAUSE_ID` int DEFAULT NULL,
  `CLAIM_ID` int DEFAULT NULL,
  `CLAIM_SUB_TYPE` varchar(200) DEFAULT NULL,
  `DATE_OF_EVENT` date DEFAULT NULL,
  `DATE_OF_ONSET` date DEFAULT NULL,
  `EVENT_ID` int NOT NULL AUTO_INCREMENT,
  `OTHERS_SPECIFY` varchar(200) DEFAULT NULL,
  `POLICY_STATUS_ON_EVENT` varchar(200) DEFAULT NULL,
  `SU_CLAUSE_APPLICABLE` varchar(200) DEFAULT NULL,
  `SU_CLAUSE_TYPE` varchar(200) DEFAULT NULL,
  `TYPE_OF_CLAIM` varchar(200) DEFAULT NULL,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`EVENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_fraud_flags_mapping` (
  `ID` int DEFAULT NULL,
  `CLAIM_ID` int DEFAULT NULL,
  `FRAUD_ID` int DEFAULT NULL,
  `USER_REMARKS` text,
  `USER_ID` text,
  `CREATEDON` text,
  `CREATEDBY` text,
  `MODIFIEDON` text,
  `MODIFIEDBY` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_fraud_master` (
  `FRAUD_ID` int DEFAULT NULL,
  `SOURCE` text,
  `REASON` text,
  `PAST_CLAIMS` text,
  `USER_ID` text,
  `CLIENT_ID` int DEFAULT NULL,
  `HOSPITAL_ID` text,
  `ADVISOR_ID` text,
  `STATUS` text,
  `CREATEDON` datetime DEFAULT NULL,
  `CREATEDBY` text,
  `MODIFIEDON` text,
  `MODIFIEDBY` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_new_terms_plan_master` (
  `PRODUCT_NAME` text,
  `PRODUCT_CODE` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_other_insurance` (
  `CLAIM_ID` int DEFAULT NULL,
  `CLAIM_STATUS` varchar(200) DEFAULT NULL,
  `COMPANY` varchar(200) DEFAULT NULL,
  `INSURANCE_TYPE` varchar(200) DEFAULT NULL,
  `OTHER_INSR_ID` int NOT NULL AUTO_INCREMENT,
  `POLICY_NUMBER` varchar(200) DEFAULT NULL,
  `POLICY_STATUS` varchar(200) DEFAULT NULL,
  `SUMASSURED` varchar(200) DEFAULT NULL,
  `TAKEN_ON` date DEFAULT NULL,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`OTHER_INSR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_past_illness_details` (
  `PAST_ILLNESS_ID` int DEFAULT NULL,
  `CLAIM_ID` int DEFAULT NULL,
  `ILLNESS` text,
  `OTHERS_SPECIFY` text,
  `DATE_OF_DX` text,
  `DURATION_MONTHS` int DEFAULT NULL,
  `DURATION_YEARS` int DEFAULT NULL,
  `REMARKS` text,
  `CREATEDON` text,
  `CREATEDBY` text,
  `MODIFIEDON` text,
  `MODIFIEDBY` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_policy_bre` (
  `ACC_OPTED` varchar(200) DEFAULT NULL,
  `AMOUNT_PAID` decimal(15,2) DEFAULT NULL,
  `AMOUNT_PAYABLE` decimal(15,2) DEFAULT NULL,
  `CC_OPTED` varchar(200) DEFAULT NULL,
  `CLAIM_ID` int NOT NULL,
  `FIN_TRANSACTION_POST_DOD` varchar(200) DEFAULT NULL,
  `FIRST_IBR_INSTALLMENT` varchar(200) DEFAULT NULL,
  `GUARANTEED_ADDITIONS` varchar(200) DEFAULT NULL,
  `INTERIM_BONUS` decimal(15,2) DEFAULT NULL,
  `INVESTMENT_FUND` varchar(200) DEFAULT NULL,
  `MATURITY_DATE` date DEFAULT NULL,
  `PARTIAL_WDWL_AMOUNT` varchar(200) DEFAULT NULL,
  `POLICY_NUM` varchar(200) NOT NULL,
  `PREMIUM` varchar(200) DEFAULT NULL,
  `REINSTATEMENT_DATE` date DEFAULT NULL,
  `REINSTATEMENT_PERIOD` varchar(200) DEFAULT NULL,
  `REVISIONARY_BONUS` varchar(200) DEFAULT NULL,
  `SA_INCREASED_FLAG` varchar(200) DEFAULT NULL,
  `SA_INCREASE_DATE` date DEFAULT NULL,
  `TERMINAL_BONUS` varchar(200) DEFAULT NULL,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_portfolio_master` (
  `PRODUCT_NAME` text,
  `PRODUCT_CODE` text,
  `PRODUCT_SUM_ASSURED` text,
  `PORTFOLIO_TYPE` text,
  `PRODUCT_SUBTYPE` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_priority_flags_mapping` (
  `ID` int DEFAULT NULL,
  `CLAIM_ID` int DEFAULT NULL,
  `PRIORITY_ID` int DEFAULT NULL,
  `REMARKS` text,
  `CREATEDON` text,
  `CREATEDBY` text,
  `MODIFIEDON` text,
  `MODIFIEDBY` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_priority_master` (
  `PRIORITY_ID` int DEFAULT NULL,
  `SOURCE` text,
  `REASON` text,
  `REMARKS` text,
  `USER_ID` text,
  `CREATEDON` text,
  `CREATEDBY` text,
  `MODIFIEDON` text,
  `MODIFIEDBY` text,
  `CLAIM_ID` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_product_details` (
  `PRODUCT_NAME` text,
  `PRODUCT_CODE` text,
  `PRODUCT_TYPE` text,
  `PRODUCT_CATEGORY` text,
  `PRODUCT_FLAG` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_rider_details` (
  `BRE_RIDER_CODE` varchar(200) DEFAULT NULL,
  `CASE_ID` varchar(200) DEFAULT NULL,
  `CLAIM_ID` int DEFAULT NULL,
  `DECISION_CLAUSE` varchar(200) DEFAULT NULL,
  `DECISION_PRI` varchar(200) DEFAULT NULL,
  `DECISION_REASON_PRI` varchar(200) DEFAULT NULL,
  `DECISION_REASON_SEC` varchar(200) DEFAULT NULL,
  `DECISION_REMARKS_PRI` varchar(200) DEFAULT NULL,
  `DECISION_REMARKS_SEC` varchar(200) DEFAULT NULL,
  `DECISION_SEC` varchar(200) DEFAULT NULL,
  `POLICY_ID` varchar(200) NOT NULL,
  `RIDER_ACTIVE` varchar(200) DEFAULT NULL,
  `RIDER_AMOUNT_PAID` varchar(200) DEFAULT NULL,
  `RIDER_AVAILABLE_SA` int DEFAULT NULL,
  `RIDER_CESSATION_DATE` date DEFAULT NULL,
  `RIDER_CODE` varchar(200) DEFAULT NULL,
  `RIDER_CODE_SA` varchar(200) DEFAULT NULL,
  `RIDER_COMPONENT_CODE` varchar(200) DEFAULT NULL,
  `RIDER_ELIGIBILITY` varchar(200) DEFAULT NULL,
  `RIDER_FIRSTIBR_INSTALLMENT` varchar(200) DEFAULT NULL,
  `RIDER_ID` int NOT NULL AUTO_INCREMENT,
  `RIDER_INTERIM_BONUS` varchar(200) DEFAULT NULL,
  `RIDER_NAME` varchar(200) DEFAULT NULL,
  `RIDER_PREMIUM` varchar(200) DEFAULT NULL,
  `RIDER_RCD` date DEFAULT NULL,
  `RIDER_REVISIONARY_BONUS` varchar(200) DEFAULT NULL,
  `RIDER_SA` varchar(200) DEFAULT NULL,
  `RIDER_STATUS` varchar(200) DEFAULT NULL,
  `RIDER_TERM` varchar(200) DEFAULT NULL,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`RIDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_rider_mapping_codes` (
  `RIDER_COMPONENT_CODE` text,
  `RIDER_PAYOUT_CODE` text,
  `RIDERCOMPONENT_TYPE` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `caps_transaction_bre` (
  `CLAIM_ID` int DEFAULT NULL,
  `TRAP_SCORE_DATE` text,
  `ASSESSOR_NAME` text,
  `TRAP_SCORE` double DEFAULT NULL,
  `ASSESSOR_ID` text,
  `TRAP_ID` int DEFAULT NULL,
  `TRAP_REMARKS` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `case_reasons` (
  `reason` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `case_trigger` (
  `CASE_TRIGGER_ID` int NOT NULL AUTO_INCREMENT,
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `REASON` varchar(200) DEFAULT NULL,
  `REMARKS` varchar(4000) DEFAULT NULL,
  `THE_DATE` date DEFAULT NULL,
  `TRIGGERED_TO` varchar(200) DEFAULT NULL,
  `STATUS` varchar(200) DEFAULT NULL,
  `CREATEDON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` varchar(200) DEFAULT NULL,
  `MODIFIEDON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIEDBY` varchar(200) DEFAULT NULL,
  `DDU_SR_CALL_LOG` varchar(200) DEFAULT NULL,
  `PRIORITY_FLAG` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`CASE_TRIGGER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `cause_event` (
  `CLAIM_ID` varchar(255) NOT NULL,
  `TYPE_OF_CLAIM` varchar(255) DEFAULT NULL,
  `CAUSE_CODE` varchar(255) DEFAULT NULL,
  `CAUSE_DESCRIPTION` varchar(255) DEFAULT NULL,
  `CAUSE_CATEGORY` varchar(255) DEFAULT NULL,
  `CAUSE_OF_CLAIM` varchar(255) DEFAULT NULL,
  `IF_OTHERS_SPECIFY` varchar(255) DEFAULT NULL,
  `DATE_OF_EVENT` date DEFAULT NULL,
  `POL_STATUS_ON_EVENT` varchar(255) DEFAULT NULL,
  `CLAIM_SUB_TYPE` varchar(255) DEFAULT NULL,
  `CLAIM_REGISTRATION_TYPE` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CLAIM_ID`),
  UNIQUE KEY `cause_event__c_l_a_i_m__i_d` (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `cause_of_claim` (
  `CAUSE_ID` int DEFAULT NULL,
  `CLAIM_CAUSE_CODE` text,
  `CLAIM_CAUSE_DESC` text,
  `STATUS` text,
  `CREATEDON` text,
  `CREATEDBY` text,
  `MODIFIEDON` text,
  `MODIFIEDBY` text,
  `CLAIMTYPE` text,
  `CLAIM_SUB_TYPE` text,
  `CAUSE_CATEGORY` text,
  `CLAIM_REGISTRATION_TYPE` text,
  `IIB_CAUSE_CODE` text,
  `IIB_CAUSE_DESC` text,
  `CAUSE0F_CLAIMCATEGORY` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `cause_of_claim_master` (
  `CAUSE_ID` int DEFAULT NULL,
  `CLAIM_CAUSE_CODE` text,
  `CLAIM_CAUSE_DESC` text,
  `STATUS` text,
  `CREATEDON` text,
  `CREATEDBY` text,
  `MODIFIEDON` datetime DEFAULT NULL,
  `MODIFIEDBY` text,
  `CLAIMTYPE` text,
  `CLAIM_SUB_TYPE` text,
  `CAUSE_CATEGORY` text,
  `CLAIM_REGISTRATION_TYPE` text,
  `IIB_CAUSE_CODE` text,
  `IIB_CAUSE_DESC` text,
  `CAUSE0F_CLAIMCATEGORY` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `claim_questions` (
  `CLAIM_ID` int NOT NULL,
  `QUESTION0` varchar(255) DEFAULT NULL,
  `QUESTION1` varchar(255) DEFAULT NULL,
  `QUESTION2` varchar(255) DEFAULT NULL,
  `QUESTION3` varchar(255) DEFAULT NULL,
  `QUESTION4` varchar(255) DEFAULT NULL,
  `QUESTION5` varchar(255) DEFAULT NULL,
  `QUESTION6` varchar(255) DEFAULT NULL,
  `QUESTION7` varchar(255) DEFAULT NULL,
  `QUESTION8` varchar(255) DEFAULT NULL,
  `QUESTION9` varchar(255) DEFAULT NULL,
  `QUESTION10` varchar(255) DEFAULT NULL,
  `QUESTION11` varchar(255) DEFAULT NULL,
  `QUESTION12` varchar(255) DEFAULT NULL,
  `QUESTION13` varchar(255) DEFAULT NULL,
  `QUESTION14` varchar(255) DEFAULT NULL,
  `QUESTION15` varchar(255) DEFAULT NULL,
  `QUESTION16` varchar(255) DEFAULT NULL,
  `QUESTION17` varchar(255) DEFAULT NULL,
  `QUESTION18` varchar(255) DEFAULT NULL,
  `QUESTION19` varchar(255) DEFAULT NULL,
  `QUESTION20` varchar(255) DEFAULT NULL,
  `QUESTION21` varchar(255) DEFAULT NULL,
  `QUESTION22` varchar(255) DEFAULT NULL,
  `QUESTION23` varchar(255) DEFAULT NULL,
  `QUESTION24` varchar(255) DEFAULT NULL,
  `QUESTION25` varchar(255) DEFAULT NULL,
  `QUESTION26` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `claim_sequence` (
  `ID` int DEFAULT NULL,
  `SEQ_NO` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `claimant_details` (
  `CLAIM_ID` int DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `CLIENT_ID` varchar(255) DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `AGE` int DEFAULT NULL,
  `GENDER` varchar(10) DEFAULT 'Male',
  `RISK_INDICATOR` varchar(255) DEFAULT NULL,
  `ROLE` varchar(50) DEFAULT 'Proposer',
  `RELATION_WITH_LIFE_ASR` varchar(255) DEFAULT NULL,
  `ID_NUMBER` varchar(255) DEFAULT NULL,
  `COUNTRY` varchar(255) DEFAULT 'ALGERIA (E Da)',
  `STATE` varchar(255) DEFAULT 'Andaman and Nico',
  `PINCODE` varchar(10) DEFAULT NULL,
  `NATIONALITY` varchar(50) DEFAULT 'Indian',
  `OCCUPATION` varchar(255) DEFAULT NULL,
  `PAN_NO` varchar(25) DEFAULT NULL,
  `EMAIL_UNAVAILABILITY_REASON` varchar(255) DEFAULT 'Email ID is not available',
  `IS_POLITICALLY_EXPOSED` varchar(10) DEFAULT 'Yes',
  `ROAD` varchar(255) DEFAULT NULL,
  `EMAIL_ID` varchar(255) DEFAULT NULL,
  `MOBILE_NO` varchar(15) DEFAULT NULL,
  `OTHER_MOBILE_NO` varchar(15) DEFAULT NULL,
  `AREA` varchar(255) DEFAULT NULL,
  `CITY` varchar(255) DEFAULT NULL,
  `TEL_NO` varchar(15) DEFAULT NULL,
  `PAN_VALID_FLAG` varchar(255) DEFAULT NULL,
  `FLAT` varchar(255) DEFAULT NULL,
  `ACCUITY_RISK_INDICATOR` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `claims` (
  `CLAIM_ID` int NOT NULL AUTO_INCREMENT,
  `CASE_ID` int DEFAULT NULL,
  `INITIATION_DATE` date DEFAULT NULL,
  `CLAIM_TYPE` varchar(50) DEFAULT NULL,
  `PORTFOLIO` varchar(50) DEFAULT NULL,
  `POLICY_STATUS` varchar(10) DEFAULT NULL,
  `INITIMATION_DATE` timestamp NULL DEFAULT NULL,
  `SOURCE` varchar(50) DEFAULT NULL,
  `PLACE_OF_CLAIM` varchar(100) DEFAULT NULL,
  `LIFE_ASR_STATUS` varchar(20) DEFAULT NULL,
  `DATE_OF_DEATH` date DEFAULT NULL,
  `DATE_OF_DEATH_REG` date DEFAULT NULL,
  `CALL_ID` varchar(50) DEFAULT NULL,
  `USER_ID` varchar(50) DEFAULT NULL,
  `CLAIM_STATUS` varchar(50) DEFAULT NULL,
  `CLAIM_ACTIVITY_STATUS` varchar(100) DEFAULT NULL,
  `ADDITIONAL_ATTR_1` int DEFAULT NULL,
  `ADDITIONAL_ATTR_2` varchar(100) DEFAULT NULL,
  `DECISION_PRI` varchar(50) DEFAULT NULL,
  `DECISION_SEC` varchar(50) DEFAULT NULL,
  `DECISION_REASON_PRI` varchar(100) DEFAULT NULL,
  `DECISION_REASON_SEC` varchar(100) DEFAULT NULL,
  `DECISION_REMARKS_PRI` varchar(100) DEFAULT NULL,
  `DECISION_REMARKS_SEC` varchar(100) DEFAULT NULL,
  `DECISION_CLAUSE` varchar(100) DEFAULT NULL,
  `VERBAL_INTMTN_DATE` date DEFAULT NULL,
  `IS_SAMPLED` tinyint(1) DEFAULT NULL,
  `IS_VERIFIED` tinyint(1) DEFAULT NULL,
  `VERBAL_SOURCE` varchar(50) DEFAULT NULL,
  `VERBAL_DATEOFDEATH` date DEFAULT NULL,
  `VERBAL_EVENT` varchar(100) DEFAULT NULL,
  `VERBAL_REMARKS` varchar(200) DEFAULT NULL,
  `POLICY_STATUS_DOD` varchar(50) DEFAULT NULL,
  `PORTFOLIO_SUBTYPE` varchar(50) DEFAULT NULL,
  `DATE_OF_CREMATION` date DEFAULT NULL,
  `DEATHFLAG` tinyint(1) DEFAULT NULL,
  `JOINTFLAG` tinyint(1) DEFAULT NULL,
  `FCR_DAY` int DEFAULT NULL,
  `FCR_DATE` date DEFAULT NULL,
  `BRANCH_CODE` varchar(50) DEFAULT NULL,
  `PAYOUT_ID` int DEFAULT NULL,
  `BASE_LDR` varchar(50) DEFAULT NULL,
  `KYC_LDR` varchar(50) DEFAULT NULL,
  `HOLDING_LETTER_SENT` tinyint(1) DEFAULT NULL,
  `HOLDING_FLAG` tinyint(1) DEFAULT NULL,
  `ASSESSMENT_USERID` varchar(50) DEFAULT NULL,
  `ASSESSMENT_USERNAME` varchar(100) DEFAULT NULL,
  `APPROVER_USERID` varchar(50) DEFAULT NULL,
  `APPROVER_USERNAME` varchar(100) DEFAULT NULL,
  `DECISION_PUSHFLAG` tinyint(1) DEFAULT NULL,
  `INTIMATION_PUSHFLAG` tinyint(1) DEFAULT NULL,
  `DEATHAPPROVALFLAG` tinyint(1) DEFAULT NULL,
  `POLICY_STATUS_TEMP` varchar(50) DEFAULT NULL,
  `DMS_FLAG` tinyint(1) DEFAULT NULL,
  `REUPD_REASON` varchar(200) DEFAULT NULL,
  `ASSESSOR_MAPPING_FLAG` tinyint(1) DEFAULT NULL,
  `REQ_USERID` varchar(50) DEFAULT NULL,
  `REQ_USERNAME` varchar(100) DEFAULT NULL,
  `HOLD_LETTER_USERID` varchar(50) DEFAULT NULL,
  `HOLD_LETTER_USERNAME` varchar(100) DEFAULT NULL,
  `RISK_USERID` varchar(50) DEFAULT NULL,
  `RISK_USERNAME` varchar(100) DEFAULT NULL,
  `EARLY_CLAIM` tinyint(1) DEFAULT NULL,
  `REPD_CODE` varchar(50) DEFAULT NULL,
  `DATE_OF_DISABILITY` date DEFAULT NULL,
  `ADBR_FLAG` tinyint(1) DEFAULT NULL,
  `ADBR_RCD_FLAG` tinyint(1) DEFAULT NULL,
  `DATE_OF_ACCIDENT` date DEFAULT NULL,
  `DECLARED_BY_DOCTOR` varchar(255) DEFAULT NULL,
  `FIR_PM_RECEIVED` varchar(255) DEFAULT NULL,
  `CLAIM_BENEFIT_OPTION` varchar(100) DEFAULT NULL,
  `OTHER_PLACE_OF_DEATH` varchar(100) DEFAULT NULL,
  `BOND_TYPE` varchar(50) DEFAULT NULL,
  `EAGLE_DOC_FLAG` tinyint(1) DEFAULT NULL,
  `EAGLE_MAKERCHECKER_FLAG` tinyint(1) DEFAULT NULL,
  `EAGLE_RULE_FLAG` tinyint(1) DEFAULT NULL,
  `POLICY_STATUS_REMARK` varchar(200) DEFAULT NULL,
  `RECOVERY_PREMIUM_FLAG` tinyint(1) DEFAULT NULL,
  `OLD_PTD` int DEFAULT NULL,
  `NEW_PTD` int DEFAULT NULL,
  `REINSURANCE_DATE` date DEFAULT NULL,
  `REINSURANCE_REMARK` varchar(200) DEFAULT NULL,
  `RECOVERY_PREMIUM_REMARK` varchar(200) DEFAULT NULL,
  `GRACE_PERIOD_REMARK_PRE` varchar(200) DEFAULT NULL,
  `GRACE_PERIOD_REMARK_SEC` varchar(200) DEFAULT NULL,
  `SOURCE_HIT` tinyint(1) DEFAULT NULL,
  `CFS_HIT_COUNT` int DEFAULT NULL,
  `IIB_ENQUIRY_CHECK` tinyint(1) DEFAULT NULL,
  `REQ_LETTER_SENT` tinyint(1) DEFAULT NULL,
  `PARTIALPAYOUT_DECISION` varchar(100) DEFAULT NULL,
  `PARTIALPAYOUT_REMARK` varchar(200) DEFAULT NULL,
  `PARTIALPAYOUT_STATUS` tinyint(1) DEFAULT NULL,
  `PARTIALPAYOUT_CTM_FLAG` tinyint(1) DEFAULT NULL,
  `PARTIALPAYOUT_CTM_STATUS` varchar(100) DEFAULT NULL,
  `PARTIALPAYOUT_CTM_REMARK` varchar(200) DEFAULT NULL,
  `PARTIALPAYOUT_CTM_DATE` date DEFAULT NULL,
  `PARTIALPAYOUT_ASS_ELIGIBLE` tinyint(1) DEFAULT NULL,
  `PARTIALPAYOUT_ASSESSMENT_ID` int DEFAULT NULL,
  `PARTIALPAYOUT_APPROVER_ID` int DEFAULT NULL,
  `PARTIALPAYOUT_CONFIRM_REMARK` varchar(200) DEFAULT NULL,
  `LA_DATE_OF_INTIMATION` date DEFAULT NULL,
  `LA_DATE_OF_DEATH` date DEFAULT NULL,
  `LA_CAUSE_OF_DEATH` varchar(100) DEFAULT NULL,
  `LA_REG_PARAM_CHECK` tinyint(1) DEFAULT NULL,
  `LA_RISK_CESSATION_DATE` date DEFAULT NULL,
  `REG_DETAILS_MISMATCH_FLAG` tinyint(1) DEFAULT NULL,
  `REG_DETAILS_MISMATCH_PARAMETER` varchar(200) DEFAULT NULL,
  `NEW_DATE_OF_DEATH` date DEFAULT NULL,
  `REVERSE_CLAIM_FLAG` tinyint(1) DEFAULT NULL,
  `RE_REGISTER_CLAIM_FLAG` tinyint(1) DEFAULT NULL,
  `ABNP_FLAG` tinyint(1) DEFAULT NULL,
  `HALF_DEATH_FLAG` tinyint(1) DEFAULT NULL,
  `COVID_DIAGNOSIS_DATE` date DEFAULT NULL,
  `COVID_HOSPITALIZATION_DATE` date DEFAULT NULL,
  `CTM_PICKED_FLAG` tinyint(1) DEFAULT NULL,
  `APPROVER_NAME_CHIEF_OPERATION` varchar(100) DEFAULT NULL,
  `APPROVAL_DATE_CHIEF_OPERATION` date DEFAULT NULL,
  `APPROVER_NAME_FINANCE_HEAD` varchar(100) DEFAULT NULL,
  `APPROVAL_DATE_FINANCE_HEAD` date DEFAULT NULL,
  `DFP_UPLOAD_FLAG` tinyint(1) DEFAULT NULL,
  `DFP_DOWNLOAD_FLAG` tinyint(1) DEFAULT NULL,
  `WHATSAPP_FLAG` varchar(255) DEFAULT NULL,
  `SR_CALLOG` varchar(200) DEFAULT NULL,
  `REMARK` varchar(500) DEFAULT NULL,
  `PRODUCT_SUBTYPE` varchar(100) DEFAULT NULL,
  `BENEFIT_OPTION` varchar(100) DEFAULT NULL,
  `CLAIM_NUMBER` varchar(50) DEFAULT NULL,
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `MODIFIED_BY` varchar(50) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS` varchar(50) DEFAULT NULL,
  `ROLE` varchar(50) DEFAULT NULL,
  `POLICY_ID` varchar(50) DEFAULT NULL,
  `ASSIGNED_TO` varchar(255) DEFAULT NULL,
  `CLAIMANT_ACUITY_DECISION` varchar(20) DEFAULT 'NOT FLAGGED',
  `PAYEE_ACUITY_DECISION` varchar(20) DEFAULT 'NOT FLAGGED',
  `FINAL_ACUITY_DECISION` varchar(20) DEFAULT 'NOT FLAGGED',
  PRIMARY KEY (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `clientdetails` (
  `id` int NOT NULL AUTO_INCREMENT,
  `policyNumber` varchar(255) NOT NULL,
  `Income` int DEFAULT NULL,
  `ClientID` varchar(255) DEFAULT NULL,
  `Name` varchar(255) DEFAULT NULL,
  `Gender` varchar(255) DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `MaritalStatus` varchar(255) DEFAULT NULL,
  `HNIFlag` varchar(255) DEFAULT NULL,
  `ResStatus` varchar(255) DEFAULT NULL,
  `Qualification` varchar(255) DEFAULT NULL,
  `Education` varchar(255) DEFAULT NULL,
  `TelNo` bigint DEFAULT NULL,
  `MobileNo` bigint DEFAULT NULL,
  `Flat` varchar(255) DEFAULT NULL,
  `Road` varchar(255) DEFAULT NULL,
  `Area` varchar(255) DEFAULT NULL,
  `City` varchar(255) DEFAULT NULL,
  `Pincode` int DEFAULT NULL,
  `RiskIndicator` int DEFAULT NULL,
  `OccCode` varchar(255) DEFAULT NULL,
  `AgeProof` varchar(255) DEFAULT NULL,
  `State` varchar(255) DEFAULT NULL,
  `OccDesc` varchar(255) DEFAULT NULL,
  `LifeFlag` varchar(255) DEFAULT NULL,
  `Country` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `common_and_rider_details` (
  `REQ_MAPPING_ID` int DEFAULT NULL,
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `REQUIREMENT_TYPE` varchar(200) DEFAULT NULL,
  `REQUIREMENT_NAME` varchar(200) DEFAULT NULL,
  `SOURCE` varchar(200) DEFAULT NULL,
  `TRIGGERED_BY` varchar(200) DEFAULT NULL,
  `TRIGGER_DATE` date DEFAULT NULL,
  `STATUS` varchar(200) DEFAULT NULL,
  `RECEIPT_DATE` date DEFAULT NULL,
  `REMARKS` varchar(400) DEFAULT NULL,
  `DOC_UPLOADED` varchar(200) DEFAULT NULL,
  `DOCUMENT_PATH` varchar(200) DEFAULT NULL,
  `BASE_LDR` date DEFAULT NULL,
  `KYC_LDR` date DEFAULT NULL,
  `RIDER_LDR` date DEFAULT NULL,
  `UPLOAD` varchar(200) DEFAULT NULL,
  `CREATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `TYPE` varchar(200) DEFAULT NULL,
  `REQ_FLAG` varchar(200) DEFAULT NULL,
  `DOC_LDR` date DEFAULT NULL,
  `RECEIVED_BY` varchar(200) DEFAULT NULL,
  `REQUIREMENT_CATEGORY` varchar(200) DEFAULT NULL,
  `MILESTONE` varchar(200) DEFAULT NULL,
  `INTERNALORCUSTOMER` varchar(200) DEFAULT NULL,
  `REQUIREMENT_DOC_TYPE` varchar(200) DEFAULT NULL,
  `LEDRD` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `contact_details` (
  `CLAIM_ID` int NOT NULL,
  `SUSPICIOUS_DETAILS` varchar(255) DEFAULT NULL,
  `APP_NO` varchar(255) DEFAULT NULL,
  `POLICY_NO` varchar(255) DEFAULT NULL,
  `PRODUCT_NAME` varchar(255) DEFAULT NULL,
  `PRODUCT_CODE` varchar(255) DEFAULT NULL,
  `CDF_DATE` date DEFAULT NULL,
  `TEL_NO` varchar(15) DEFAULT NULL,
  `POLICY_AGE` varchar(50) DEFAULT NULL,
  `MOBILE_NO_CHANGE` varchar(15) DEFAULT NULL,
  `EMAIL_ID_CHANGE` varchar(255) DEFAULT NULL,
  `POLICY_AGE1` decimal(20,2) DEFAULT NULL,
  `EKIT_PRINTED` varchar(255) DEFAULT NULL,
  `EKIT_DATE` date DEFAULT NULL,
  `NAME_CHANGE_DECL` varchar(255) DEFAULT NULL,
  `KNOWN_TO_LIFE_ASR` varchar(255) DEFAULT NULL,
  `PROP_DATE` date DEFAULT NULL,
  `RELN` varchar(255) DEFAULT NULL,
  `OUTSTANDING_LOAN_SCHED` varchar(255) DEFAULT NULL,
  `ISSUE_DATE` date DEFAULT NULL,
  `CLAIMS_RUPIDIATE` varchar(255) DEFAULT NULL,
  `OUTSTANDING_LOAN_NO_C` varchar(255) DEFAULT NULL,
  `PAID_TO_DATE` date DEFAULT NULL,
  `RCD` varchar(255) DEFAULT NULL,
  `RISK_DATE` date DEFAULT NULL,
  `PREM_FREQ` varchar(50) DEFAULT NULL,
  `TERM` int DEFAULT NULL,
  `PREM_STATUS` varchar(50) DEFAULT NULL,
  `PREM_PAID_YRS` int DEFAULT NULL,
  `FIRST_PREM_DEP` decimal(15,2) DEFAULT NULL,
  `TOTAL_PREM_PAID` decimal(15,2) DEFAULT NULL,
  `ORIGINAL_SA` decimal(15,2) DEFAULT NULL,
  `CURRENT_SA` decimal(15,2) DEFAULT NULL,
  `AVAILABLE_SA` decimal(15,2) DEFAULT NULL,
  `ACTUAL_VALUE` decimal(15,2) DEFAULT NULL,
  `ESTIMATED_VALUE` decimal(15,2) DEFAULT NULL,
  `MATURITY_VALUE` decimal(15,2) DEFAULT NULL,
  `GUAR_FUND` varchar(255) DEFAULT NULL,
  `CLAIM_STATUS` varchar(50) DEFAULT NULL,
  `CASH_VALUE` decimal(15,2) DEFAULT NULL,
  `CUST_INDICATOR` varchar(255) DEFAULT NULL,
  `EXCESS_PREM` decimal(15,2) DEFAULT NULL,
  `FIN_POST` varchar(255) DEFAULT NULL,
  `OUTSTANDING_LOAN` decimal(15,2) DEFAULT NULL,
  `ADVISOR_CODE` varchar(255) DEFAULT NULL,
  `MEDICAL_DATE` date DEFAULT NULL,
  `MED_TRIG` varchar(255) DEFAULT NULL,
  `MALPRACTICE_CODE` varchar(255) DEFAULT NULL,
  `ADVOCATE` varchar(255) DEFAULT NULL,
  `ADVISOR_STATUS` varchar(50) DEFAULT NULL,
  `ASSIGNMENT` varchar(255) DEFAULT NULL,
  `SALES_CHANNEL` varchar(255) DEFAULT NULL,
  `UM_CODE` varchar(255) DEFAULT NULL,
  `UW_DEC` varchar(255) DEFAULT NULL,
  `UW_DEC_DATE` date DEFAULT NULL,
  `RES_XRT` varchar(255) DEFAULT NULL,
  `MED_CODE` varchar(255) DEFAULT NULL,
  `IND_CODE` varchar(255) DEFAULT NULL,
  `IND_DESC` varchar(255) DEFAULT NULL,
  `AGENT_TYPE` varchar(255) DEFAULT NULL,
  `AGENT_TYPE_DESC` varchar(255) DEFAULT NULL,
  `STAT_CODE` varchar(255) DEFAULT NULL,
  `BASE_COMPONENT` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `RIDER_CODE` varchar(255) DEFAULT NULL,
  `RIDER_SA` varchar(200) DEFAULT NULL,
  `RIDER_RCD` date DEFAULT NULL,
  `RIDER_TERM` varchar(200) DEFAULT NULL,
  `RIDER_STATUS` varchar(200) DEFAULT NULL,
  `RIDER_CESSATION_DATE` date DEFAULT NULL,
  PRIMARY KEY (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `contractdetails` (
  `id` int NOT NULL AUTO_INCREMENT,
  `policyNumber` varchar(255) NOT NULL,
  `TotalPremPaid` int DEFAULT NULL,
  `PolicyStatus` varchar(255) DEFAULT NULL,
  `ProductName` varchar(255) DEFAULT NULL,
  `ProductCode` varchar(255) DEFAULT NULL,
  `Term` int DEFAULT NULL,
  `SumAssured` int DEFAULT NULL,
  `CurrentStatus` varchar(255) DEFAULT NULL,
  `RCD` date DEFAULT NULL,
  `PolicyIssueDate` date DEFAULT NULL,
  `PaidToDate` date DEFAULT NULL,
  `UWDate` date DEFAULT NULL,
  `UWDecision` varchar(255) DEFAULT NULL,
  `AdvisorCode` varchar(255) DEFAULT NULL,
  `AdvisorName` varchar(255) DEFAULT NULL,
  `PremFreq` varchar(255) DEFAULT NULL,
  `PremStatus` varchar(255) DEFAULT NULL,
  `CurrentSA` int DEFAULT NULL,
  `ClientIndicatorCode` varchar(255) DEFAULT NULL,
  `ClientIndicatorDesc` varchar(255) DEFAULT NULL,
  `BaseComponent` varchar(255) DEFAULT NULL,
  `RiskCessDate` date DEFAULT NULL,
  `FundValue` int DEFAULT NULL,
  `AdvisorTel` varchar(255) DEFAULT NULL,
  `PropRECDDate` date DEFAULT NULL,
  `ApplicationNo` varchar(255) DEFAULT NULL,
  `OriginalSA` int DEFAULT NULL,
  `BilledDate` date DEFAULT NULL,
  `ExcessPrem` int DEFAULT NULL,
  `AdvisorStatus` varchar(255) DEFAULT NULL,
  `GuaranteedAddition` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `countries` (
  `name` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `decision_accessor` (
  `CLAIM_ID` varchar(255) NOT NULL,
  `REQ_LETTER_SENT` varchar(100) DEFAULT NULL,
  `REMARKS` varchar(255) DEFAULT NULL,
  `BASE` varchar(50) DEFAULT NULL,
  `FUND` varchar(50) DEFAULT NULL,
  `INTERIM` varchar(50) DEFAULT NULL,
  `GA` varchar(50) DEFAULT NULL,
  `OT_BONUS` varchar(50) DEFAULT NULL,
  `EXCESS_PREMIUM` varchar(50) DEFAULT NULL,
  `TERMINAL_BONUS` varchar(50) DEFAULT NULL,
  `REV_BONUS` varchar(50) DEFAULT NULL,
  `INTEREST` varchar(50) DEFAULT NULL,
  `PENAL_INTEREST1` varchar(50) DEFAULT NULL,
  `ADBRSA` varchar(50) DEFAULT NULL,
  `REQ_DAMT` varchar(50) DEFAULT NULL,
  `LTARSA` varchar(50) DEFAULT NULL,
  `PARTIAL_WDWT` varchar(50) DEFAULT NULL,
  `PPYRSA` varchar(50) DEFAULT NULL,
  `IBRSA` varchar(50) DEFAULT NULL,
  `MSARSA` varchar(50) DEFAULT NULL,
  `CIBRSA` varchar(50) DEFAULT NULL,
  `ABRSA` varchar(50) DEFAULT NULL,
  `OTS_LOAN` varchar(50) DEFAULT NULL,
  `LOAN_NOC` varchar(50) DEFAULT NULL,
  `PREMIUM_OTS` varchar(50) DEFAULT NULL,
  `ANNUITY_PAYOUT_REMARK` varchar(255) DEFAULT NULL,
  `PAYOUT_REMARKS` varchar(255) DEFAULT NULL,
  `DECISION_AGEING` int DEFAULT NULL,
  `DECISION_AGING_REMARK` varchar(255) DEFAULT NULL,
  `TOTAL_AMT_PAYABLE` varchar(50) DEFAULT NULL,
  `PP_AMT1` varchar(50) DEFAULT NULL,
  `PP_AMT2` varchar(50) DEFAULT NULL,
  `REFUND` varchar(50) DEFAULT NULL,
  `INTEREST2` varchar(50) DEFAULT NULL,
  `CUSTOMER` varchar(100) DEFAULT NULL,
  `BANK_MPHASIGNEE` varchar(100) DEFAULT NULL,
  `TOTAL_PREMIUM` varchar(50) DEFAULT NULL,
  `EXGRATIA` varchar(50) DEFAULT NULL,
  `PENAL_INTEREST2` varchar(50) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DECISION_TABLE` varchar(100) DEFAULT NULL,
  `DECISION_REASON_TABLE` varchar(100) DEFAULT NULL,
  `DECISION` varchar(255) DEFAULT NULL,
  `DECISION_REASON` varchar(20) DEFAULT NULL,
  `RIDER_CODE` varchar(255) DEFAULT NULL,
  `RIDER_SA` varchar(200) DEFAULT NULL,
  `RIDER_RCD` date DEFAULT NULL,
  `RIDER_TERM` varchar(200) DEFAULT NULL,
  `RIDER_STATUS` varchar(200) DEFAULT NULL,
  `RIDER_CESSATION_DATE` date DEFAULT NULL,
  PRIMARY KEY (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `decision_details` (
  `CLAIM_ID` varchar(50) NOT NULL,
  `BASE_SEC` decimal(15,2) DEFAULT NULL,
  `FUND_SEC` decimal(15,2) DEFAULT NULL,
  `INTERIM_SEC` decimal(15,2) DEFAULT NULL,
  `GA_SEC` decimal(15,2) DEFAULT NULL,
  `LOAN_SCHEDULE_SEC` decimal(15,2) DEFAULT NULL,
  `PREMIUM_OTS_SEC` decimal(15,2) DEFAULT NULL,
  `EXCESS_PREMIUM_SEC` decimal(15,2) DEFAULT NULL,
  `REV_BONUS_SEC` decimal(15,2) DEFAULT NULL,
  `OTS_LOAN_SEC` decimal(15,2) DEFAULT NULL,
  `TERMINAL_BONUS_SEC` decimal(15,2) DEFAULT NULL,
  `MODIFIED_BY` varchar(100) DEFAULT NULL,
  `MODIFIED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `decision_system` (
  `CLAIM_ID` varchar(255) NOT NULL,
  `DECISION1` varchar(50) DEFAULT NULL,
  `REASON1` varchar(100) DEFAULT NULL,
  `REMARKS1` varchar(100) DEFAULT NULL,
  `DECISION2` varchar(50) DEFAULT NULL,
  `REASON2` varchar(100) DEFAULT NULL,
  `REMARKS2` varchar(100) DEFAULT NULL,
  `BASE` decimal(15,2) DEFAULT NULL,
  `ADBRSA` decimal(15,2) DEFAULT NULL,
  `TOTAL_PREM_PAID` decimal(15,2) DEFAULT NULL,
  `REFUND` decimal(15,2) DEFAULT NULL,
  `FUND` decimal(15,2) DEFAULT NULL,
  `ABRSA` decimal(15,2) DEFAULT NULL,
  `OT_BONUS` decimal(15,2) DEFAULT NULL,
  `PARTIAL_WDWT` decimal(15,2) DEFAULT NULL,
  `INTERIM` decimal(15,2) DEFAULT NULL,
  `LTARSA` decimal(15,2) DEFAULT NULL,
  `LOAN_NOC` decimal(15,2) DEFAULT NULL,
  `REV_BONUS` decimal(15,2) DEFAULT NULL,
  `GA` decimal(15,2) DEFAULT NULL,
  `IBRSA` decimal(15,2) DEFAULT NULL,
  `PREMIUM_OTS` decimal(15,2) DEFAULT NULL,
  `INTEREST` decimal(15,2) DEFAULT NULL,
  `PPYRSA` decimal(15,2) DEFAULT NULL,
  `MSARSA` decimal(15,2) DEFAULT NULL,
  `EXCESS_PREMIUM` decimal(15,2) DEFAULT NULL,
  `PENAL_INTEREST` decimal(15,2) DEFAULT NULL,
  `CIBRSA` decimal(15,2) DEFAULT NULL,
  `OTS_LOAN` decimal(15,2) DEFAULT NULL,
  `TERMINAL_BONUS` decimal(15,2) DEFAULT NULL,
  `CUSTOMER` varchar(100) DEFAULT NULL,
  `BANK` varchar(100) DEFAULT NULL,
  `DECISION_AGEING` int DEFAULT NULL,
  `TOTAL_AMT_PAYABLE` decimal(15,2) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `RIDER_CODE` varchar(255) DEFAULT NULL,
  `RIDER_SA` varchar(200) DEFAULT NULL,
  `RIDER_RCD` date DEFAULT NULL,
  `RIDER_TERM` varchar(200) DEFAULT NULL,
  `RIDER_STATUS` varchar(200) DEFAULT NULL,
  `RIDER_CESSATION_DATE` date DEFAULT NULL,
  `DECISION` varchar(100) DEFAULT NULL,
  `DECISION_REASON` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `decision_verification_and_summary` (
  `CLAIM_ID` varchar(255) NOT NULL,
  `STATUS` varchar(50) DEFAULT NULL,
  `DATE` date DEFAULT NULL,
  `VERIFIER_ID` varchar(50) DEFAULT NULL,
  `REMARKS` varchar(255) DEFAULT NULL,
  `TOTAL_NON_RISK_AMOUNT` decimal(15,2) DEFAULT NULL,
  `TOTAL_RISK_SA` decimal(15,2) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `doctor_details` (
  `DOCTOR_ID` int DEFAULT NULL,
  `CLAIM_ID` varchar(200) NOT NULL,
  `CATEGORY` varchar(200) DEFAULT NULL,
  `DOCTOR_NAME` varchar(500) DEFAULT NULL,
  `REG_NO` varchar(200) DEFAULT NULL,
  `QUALIFICATION` varchar(400) DEFAULT NULL,
  `DT_OF_FIRST_CONSUL` date DEFAULT NULL,
  `CREATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `CAUSE_OF_DEATH` varchar(500) DEFAULT NULL,
  `SEQUENCE` varchar(200) DEFAULT NULL,
  `ADDRESS_ID` varchar(400) DEFAULT NULL,
  `OTHER_QUALIFICATION` varchar(500) DEFAULT NULL,
  `MILESTONE` varchar(100) DEFAULT NULL,
  `INSTANCE_NO` int DEFAULT NULL,
  `DOC_SIGN` varchar(500) DEFAULT NULL,
  `HOSPITAL_ID` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `documentlist` (
  `documentListId` int NOT NULL AUTO_INCREMENT,
  `documentType` varchar(50) NOT NULL,
  `createdBy` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`documentListId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `eagle_screen` (
  `CLAIM_ID` int NOT NULL,
  `WITNESS_NAME_CDF` varchar(255) DEFAULT NULL,
  `LA_MOBILE_NO` varchar(15) DEFAULT NULL,
  `CENTER_NAME` varchar(255) DEFAULT NULL,
  `CENTER_ADDRESS` varchar(255) DEFAULT NULL,
  `CENTER_CONTRACT_NO` varchar(255) DEFAULT NULL,
  `DOCTOR_NAME` varchar(255) DEFAULT NULL,
  `BANK_NAME` varchar(255) DEFAULT NULL,
  `CLAIMANT_MOBILE_NO` varchar(15) DEFAULT NULL,
  `ACC_NO` varchar(20) DEFAULT NULL,
  `ACCOUNT_OPENING_DATE` date DEFAULT NULL,
  `AGENT_NAME` varchar(255) DEFAULT NULL,
  `AGENT_MOBILE_NO` varchar(15) DEFAULT NULL,
  `AGENT_CODE` varchar(50) DEFAULT NULL,
  `OCC` varchar(255) DEFAULT NULL,
  `ORG_TYPE` varchar(255) DEFAULT NULL,
  `INCOME` decimal(15,2) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ADVISOR_HISTORY_COUNT` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `established_cause` (
  `CLAIM_ID` varchar(255) NOT NULL,
  `TYPE_OF_CLAIM` varchar(255) DEFAULT NULL,
  `CAUSE_CODE` varchar(255) DEFAULT NULL,
  `CAUSE_DESCRIPTION` varchar(255) DEFAULT NULL,
  `CAUSE_CATEGORY` varchar(255) DEFAULT NULL,
  `CAUSE_OF_CLAIM` varchar(255) DEFAULT NULL,
  `IF_OTHERS_SPECIFY` varchar(255) DEFAULT NULL,
  `DATE_OF_EVENT` date DEFAULT NULL,
  `POL_STATUS_ON_EVENT` varchar(255) DEFAULT NULL,
  `CLAIM_SUB_TYPE` varchar(255) DEFAULT NULL,
  `CLAIM_REGISTRATION_TYPE` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `fraud_flags_mapping` (
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `FRAUD_ID` int DEFAULT NULL,
  `ID` int DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `USER_ID` varchar(200) DEFAULT NULL,
  `USER_REMARKS` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `hospital_details` (
  `EVENT_ID` int DEFAULT NULL,
  `CLAIM_ID` varchar(200) NOT NULL,
  `HOSPITAL_ID` varchar(200) DEFAULT NULL,
  `DT_OF_ADMN` date DEFAULT NULL,
  `DT_OF_DISCHARGE` date DEFAULT NULL,
  `CREATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `ADDRESS_ID` varchar(200) DEFAULT NULL,
  `NAME` varchar(500) DEFAULT NULL,
  `DIAGNOSIS_DT` date DEFAULT NULL,
  `OTHER_HOSPITAL_NAME` varchar(500) DEFAULT NULL,
  `CATEGORY` varchar(200) DEFAULT NULL,
  `SEQUENCE` varchar(200) DEFAULT NULL,
  `MILESTONE` varchar(100) DEFAULT NULL,
  `NATURE_OF_ILLNESS` varchar(200) DEFAULT NULL,
  `OTH_ILLNESS` varchar(200) DEFAULT NULL,
  `INSTANCE_NO` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `iib_enquiry` (
  `SEQ_NO` int DEFAULT NULL,
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `TRANSACTION_ID` varchar(200) DEFAULT NULL,
  `INPUT_PROPOSAL_POLICY_NO` varchar(200) DEFAULT NULL,
  `QUESTDBNO` varchar(200) DEFAULT NULL,
  `INPUT_MATCHING_PARAMETER` varchar(200) DEFAULT NULL,
  `QUEST_DOP_DOC` date DEFAULT NULL,
  `QUEST_SUM_ASSURED` int DEFAULT NULL,
  `QUEST_POLICY_STATUS` varchar(200) DEFAULT NULL,
  `QUEST_DATE_OF_EXIT` date DEFAULT NULL,
  `QUEST_DATE_OF_DEATH` date DEFAULT NULL,
  `QUEST_CAUSE_OF_DEATH` varchar(500) DEFAULT NULL,
  `QUEST_RECORD_LAST_UPDATED` date DEFAULT NULL,
  `QUEST_ENTITY_CAUTION_STATUS` varchar(200) DEFAULT NULL,
  `QUEST_INTERM_CAUTION_STATUS` varchar(200) DEFAULT NULL,
  `QUEST_COMPANY_NUMBER` int DEFAULT NULL,
  `IS_NEGATIVE_MATCH` varchar(200) DEFAULT NULL,
  `CREATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `PRODUCT_TYPE` varchar(200) DEFAULT NULL,
  `LINKED_NONLINKED` varchar(2000) DEFAULT NULL,
  `MEDICAL_NONMEDICAL` varchar(2000) DEFAULT NULL,
  `WHETHER_STANDARD_LIFE` varchar(2000) DEFAULT NULL,
  `REASON_FOR_DECLINE` varchar(2000) DEFAULT NULL,
  `REASON_FOR_POSTPONE` varchar(2000) DEFAULT NULL,
  `REASON_FOR_REPUDIATION` varchar(2000) DEFAULT NULL,
  `IIB_REF_NO` varchar(100) DEFAULT NULL,
  `IIB_ENQUIRY_DATE` date DEFAULT NULL,
  `IIB_STATUS` varchar(20) DEFAULT NULL,
  `IIB_POLICIES_FOUND` int DEFAULT NULL,
  `IIB_TOTAL_SA` decimal(18,2) DEFAULT NULL,
  `IIB_FRAUD_FLAG` varchar(10) DEFAULT NULL,
  `IIB_MULTIPLE_POLICY` varchar(10) DEFAULT NULL,
  `IIB_NON_DISCLOSURE` varchar(10) DEFAULT NULL,
  `IIB_REMARKS` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `inbox` (
  `inward_id` varchar(20) NOT NULL,
  `subject` mediumtext,
  `from` varchar(45) DEFAULT NULL,
  `text_body` longtext,
  `date` varchar(45) DEFAULT NULL,
  `time` varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `income_details` (
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `INCOME_ID` varchar(200) DEFAULT NULL,
  `PROOF_ID` varchar(200) DEFAULT NULL,
  `ISSUE_DATE` date DEFAULT NULL,
  `EMAIL_ID` varchar(200) DEFAULT NULL,
  `MOBILE_NO` varchar(200) DEFAULT NULL,
  `SEQ_NO` int DEFAULT NULL,
  `MODIFIED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `CREATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `FINANCIAL_YEAR` varchar(200) DEFAULT NULL,
  `INSTANCE_NO` int DEFAULT NULL,
  `PROOF_SEQ_NO` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `intimation_details` (
  `CLAIM_ID` varchar(255) NOT NULL,
  `CLAIM_TYPE` varchar(255) DEFAULT NULL,
  `POLICY_STATUS` varchar(255) DEFAULT NULL,
  `INTIMATION_TYPE` varchar(255) DEFAULT NULL,
  `INITIATION_DATE` date DEFAULT NULL,
  `INTIMATION_DATE` date DEFAULT NULL,
  `SOURCE` varchar(255) DEFAULT NULL,
  `FIR_PM_RECEIVED` varchar(50) DEFAULT NULL,
  `BOND_TYPE` varchar(255) DEFAULT NULL,
  `WHATSAPP_FLAG` varchar(10) DEFAULT NULL,
  `DECLARED_BY_DOCTOR` varchar(255) DEFAULT NULL,
  `PORTFOLIO` varchar(255) DEFAULT NULL,
  `LIFE_ASR_STATUS` varchar(255) DEFAULT NULL,
  `DATE_OF_DEATH_EVENT` date DEFAULT NULL,
  `DATE_OF_DEATH_REG` date DEFAULT NULL,
  `DATE_OF_CREMATION` date DEFAULT NULL,
  `TRANSACTION_STATUS` varchar(50) DEFAULT NULL,
  `INITIAL_POLICY_STATUS` varchar(255) DEFAULT NULL,
  `DATE_OF_ACCIDENT` date DEFAULT NULL,
  `PLACE_OF_DEATH_TI` varchar(255) DEFAULT NULL,
  `POLICY_STATUS_ON_DODDOE` varchar(255) DEFAULT NULL,
  `DEATH_CERTIFICATE` varchar(50) DEFAULT NULL,
  `DEATH_CERTIFICATE_REG_NUMBER` varchar(255) DEFAULT NULL,
  `DEATH_CERTIFICATE_REG_DATE` date DEFAULT NULL,
  `DEATH_CERTIFICATE_ISSUE_DISTRICT` varchar(255) DEFAULT NULL,
  `DEATH_CERTIFICATE_ISSUING_AUTHORITY` varchar(255) DEFAULT NULL,
  `DEATH_CERTIFICATE_ISSUE_TEHSIL` varchar(255) DEFAULT NULL,
  `DEATH_CERTIFICATE_ISSUE_STATE` varchar(255) DEFAULT NULL,
  `PLACE_OF_DEATH_ON_DC` varchar(255) DEFAULT NULL,
  `DEATH_CERTIFICATE_ISSUE_VILLAGE_BLOCK` varchar(255) DEFAULT NULL,
  `DEATH_CERTIFICATE_ISSUING_OFFICER_POSITION` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `POLICY_STATUS_EDIT_REMARK` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `lapsed_policies_master` (
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `ACC_OPTED` varchar(200) DEFAULT NULL,
  `AMOUNT_PAYABLE` varchar(200) DEFAULT NULL,
  `CALCULATED_FIELDS` varchar(200) DEFAULT NULL,
  `CCO_OPTED` varchar(200) DEFAULT NULL,
  `COMPONENT_CODE` varchar(200) DEFAULT NULL,
  `DECISION` varchar(200) DEFAULT NULL,
  `ISSUANCE_DATE` varchar(200) DEFAULT NULL,
  `POLICY_STATUS_ON_DEATH` varchar(200) DEFAULT NULL,
  `PREMIUM_PAID_YEARS` varchar(200) DEFAULT NULL,
  `PRODUCT_CODE` varchar(200) DEFAULT NULL,
  `PRODUCT_NAME` varchar(200) DEFAULT NULL,
  `REASON` varchar(200) DEFAULT NULL,
  `REMARK` varchar(200) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `letters_and_emails` (
  `SERIAL_NO` varchar(200) DEFAULT NULL,
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `LETTER_CODE` varchar(200) DEFAULT NULL,
  `LETTER_PATH` varchar(200) DEFAULT NULL,
  `TRIGGER_DATE` date DEFAULT NULL,
  `TRIGGER_BY` varchar(200) DEFAULT NULL,
  `NOT_SEND_REASON` varchar(500) DEFAULT NULL,
  `SEND_FLAG` varchar(200) DEFAULT NULL,
  `DISPATCH_DATE` date DEFAULT NULL,
  `STATUS` varchar(200) DEFAULT NULL,
  `EMAIL_ID` varchar(200) DEFAULT NULL,
  `BILL_NO` varchar(200) DEFAULT NULL,
  `REQUIREMENT_PUSH_FLAG` varchar(200) DEFAULT NULL,
  `CTM_STATUS` varchar(200) DEFAULT NULL,
  `POD` varchar(200) DEFAULT NULL,
  `FILENET_ID` varchar(500) DEFAULT NULL,
  `CREATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `SFTP_UPLOAD_STATUS` varchar(4000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `life_assured_details` (
  `CLAIM_ID` int NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `CLIENT_ID` varchar(255) DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `GENDER` varchar(10) DEFAULT 'Male',
  `MARITAL_STATUS` varchar(50) DEFAULT NULL,
  `RES_STATUS` varchar(50) DEFAULT NULL,
  `HNI_FLAG` varchar(10) DEFAULT NULL,
  `STATUS` varchar(50) DEFAULT NULL,
  `TYPE` varchar(50) DEFAULT NULL,
  `EDUCATION` varchar(255) DEFAULT NULL,
  `RISK_INDICATOR` varchar(255) DEFAULT NULL,
  `QUALIFICATION` varchar(255) DEFAULT NULL,
  `AGE_PROOF` varchar(50) DEFAULT 'Indian',
  `AGE_DESC` varchar(255) DEFAULT NULL,
  `ID_PROOF` varchar(255) DEFAULT NULL,
  `ID_NUMBER` varchar(255) DEFAULT NULL,
  `AGE_AT_DEATH` int DEFAULT NULL,
  `FLAT1` varchar(255) DEFAULT NULL,
  `ROAD1` varchar(255) DEFAULT NULL,
  `AREA1` varchar(255) DEFAULT NULL,
  `CITY1` varchar(255) DEFAULT NULL,
  `STATE1` varchar(255) DEFAULT NULL,
  `PINCODE1` varchar(10) DEFAULT NULL,
  `TEL_NO1` varchar(15) DEFAULT NULL,
  `MOBILE_NO1` varchar(15) DEFAULT NULL,
  `EMAIL_ID1` varchar(255) DEFAULT NULL,
  `EST_NAME` varchar(255) DEFAULT NULL,
  `SL` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `OCC_CATEGORY` varchar(255) DEFAULT NULL,
  `OCC_DESC` varchar(255) DEFAULT NULL,
  `INCOME` decimal(15,2) DEFAULT NULL,
  `NATURE` varchar(255) DEFAULT NULL,
  `REMARKS` varchar(255) DEFAULT NULL,
  `DESIGNATION` varchar(255) DEFAULT NULL,
  `FLAT2` varchar(255) DEFAULT NULL,
  `ROAD2` varchar(255) DEFAULT NULL,
  `AREA2` varchar(255) DEFAULT NULL,
  `CITY2` varchar(255) DEFAULT NULL,
  `PINCODE2` varchar(10) DEFAULT NULL,
  `TEL_NO2` varchar(15) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `state2` varchar(200) DEFAULT NULL,
  `email_id2` varchar(200) DEFAULT NULL,
  `mobile_no2` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `parallel_policies` (
  `PARALLEL_ID` int DEFAULT NULL,
  `POLICY_NUMBER` varchar(200) DEFAULT NULL,
  `RCD` date DEFAULT NULL,
  `PRODUCT_CODE` varchar(200) DEFAULT NULL,
  `CURRENT_SA` int DEFAULT NULL,
  `FUND_VALUE` int DEFAULT NULL,
  `POLICY_STATUS` varchar(200) DEFAULT NULL,
  `RIDER_CODE` varchar(200) DEFAULT NULL,
  `RIDER_SA` varchar(200) DEFAULT NULL,
  `LINKED` varchar(200) DEFAULT NULL,
  `CLIENT_ID` varchar(20) DEFAULT NULL,
  `CASE_ID` varchar(20) DEFAULT NULL,
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `CLAIM_STATUS` varchar(200) DEFAULT NULL,
  `DELINKED_REASON` varchar(200) DEFAULT NULL,
  `POLICY_LIFE_HEALTH` varchar(200) DEFAULT NULL,
  `CLAIM_TYPE` varchar(200) DEFAULT NULL,
  `LANAME` varchar(100) DEFAULT NULL,
  `LAID` varchar(200) DEFAULT NULL,
  `BASE_LDR` date DEFAULT NULL,
  `KYC_LDR` date DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `CASE_ID_NEW` varchar(200) DEFAULT NULL,
  `CURR_CASE_ID` varchar(20) DEFAULT NULL,
  `CLAIM_APPLICABILITY_PRE` varchar(100) DEFAULT NULL,
  `CLAIM_APPLICABILITY_SEC` varchar(100) DEFAULT NULL,
  `REMARKS_PRE` varchar(500) DEFAULT NULL,
  `REMARKS_SEC` varchar(500) DEFAULT NULL,
  `CALL_LOG` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `payee_details` (
  `CLAIM_ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `LAST_NAME` varchar(255) DEFAULT NULL,
  `CLIENT_ID` varchar(255) DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `GENDER` varchar(10) DEFAULT NULL,
  `ROLE` varchar(50) DEFAULT NULL,
  `RISK_INDICATOR` varchar(255) DEFAULT NULL,
  `ID_NUMBER` varchar(255) DEFAULT NULL,
  `RELATION_WITH_LIFE_ASR` varchar(255) DEFAULT NULL,
  `STATUS` varchar(50) DEFAULT NULL,
  `PAN_NO` varchar(25) DEFAULT NULL,
  `PAN_VALIDITY_FLAG` varchar(10) DEFAULT NULL,
  `UPDATE_PAYEE` varchar(10) DEFAULT NULL,
  `FLAT` varchar(255) DEFAULT NULL,
  `ROAD` varchar(255) DEFAULT NULL,
  `AREA` varchar(255) DEFAULT NULL,
  `STATE` varchar(255) DEFAULT NULL,
  `COUNTRY` varchar(255) DEFAULT NULL,
  `NATIONALITY` varchar(50) DEFAULT NULL,
  `PIN_CODE` varchar(10) DEFAULT NULL,
  `CITY` varchar(255) DEFAULT NULL,
  `TEL_NO` varchar(15) DEFAULT NULL,
  `MOBILE_NO` varchar(15) DEFAULT NULL,
  `EMAIL_ID` varchar(255) DEFAULT NULL,
  `ACCUITY_RISK_INDICATOR` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `place_of_death` (
  `place` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `proof_details` (
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `PROOF_TYPE` varchar(200) DEFAULT NULL,
  `DOCUMENT_TYPE` varchar(200) DEFAULT NULL,
  `ISSUE_DATE` date DEFAULT NULL,
  `DOCUMENT_ID` varchar(200) DEFAULT NULL,
  `IS_LETTER_SUBMITTED` varchar(50) DEFAULT NULL,
  `LETTER_NAME` varchar(500) DEFAULT NULL,
  `DESIGNATION` varchar(500) DEFAULT NULL,
  `SIGNATURE` varchar(100) DEFAULT NULL,
  `AGE` varchar(200) DEFAULT NULL,
  `RATION_CARD_TYPE` varchar(200) DEFAULT NULL,
  `MEMBERS` varchar(200) DEFAULT NULL,
  `SEQ_NO` varchar(200) DEFAULT NULL,
  `CREATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `MOBILE_NO` varchar(200) DEFAULT NULL,
  `MILESTONE` varchar(200) DEFAULT NULL,
  `RATION_CARD_NO` varchar(100) DEFAULT NULL,
  `OTHER_PHOTOID` varchar(100) DEFAULT NULL,
  `CATEGORY` varchar(100) DEFAULT NULL,
  `AADHAAR_MATCH` varchar(100) DEFAULT NULL,
  `CLIENT_ID` varchar(50) DEFAULT NULL,
  `PAN_VALIDITY` varchar(100) DEFAULT NULL,
  `PAN_VALIDITY_CODE` varchar(200) DEFAULT NULL,
  `PAN_HOLDER_NAME` varchar(100) DEFAULT NULL,
  `FATHER_NAME` varchar(100) DEFAULT NULL,
  `USER_FLAG` varchar(20) DEFAULT NULL,
  `PAN_STATUS` varchar(100) DEFAULT NULL,
  `PAN_NAME_MATCH` varchar(20) DEFAULT NULL,
  `DOB_MATCH` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `requirement_master` (
  `REQUIREMENT_CODE` text,
  `REQUIREMENT_DESC` text,
  `REQUIREMENT_STATUS` text,
  `REQUIREMENT_SOURCE` text,
  `REQUIREMENT_TYPE` text,
  `REQUIREMENT_CATEGORY` text,
  `REQUIREMENT_DOC_TYPE` text,
  `INTERNALORCUSTOMER` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `requirement_table` (
  `CLAIM_ID` int NOT NULL,
  `REQUIREMENT_NAME1` varchar(255) DEFAULT NULL,
  `REQUIREMENT_TYPE1` varchar(255) DEFAULT NULL,
  `SOURCE1` varchar(255) DEFAULT NULL,
  `STATUS1` varchar(255) DEFAULT NULL,
  `TRIGGERED_BY1` varchar(255) DEFAULT NULL,
  `TRIGGER_DATE1` datetime DEFAULT NULL,
  `RECEIPT_DATE1` datetime DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `requirements` (
  `REQ_MAPPING_ID` int NOT NULL AUTO_INCREMENT,
  `CLAIM_ID` int NOT NULL,
  `REQUIREMENT_TYPE` varchar(50) DEFAULT NULL,
  `REQUIREMENT_NAME` varchar(100) DEFAULT NULL,
  `SOURCE` varchar(50) DEFAULT NULL,
  `TRIGGERED_BY` varchar(50) DEFAULT NULL,
  `TRIGGERED_DATE` date DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `RECEIPT_DATE` date DEFAULT NULL,
  `REMARKS` text,
  `DOC_UPLOADED` tinyint(1) DEFAULT NULL,
  `DOCUMENT_PATH` varchar(255) DEFAULT NULL,
  `BASE_LDR` varchar(50) DEFAULT NULL,
  `KYC_LDR` varchar(50) DEFAULT NULL,
  `RIDER_LDR` varchar(50) DEFAULT NULL,
  `UPLOAD` tinyint(1) DEFAULT NULL,
  `CREATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `MODIFIED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(50) DEFAULT NULL,
  `TYPE` varchar(20) DEFAULT NULL,
  `REQ_FLAG` varchar(50) DEFAULT NULL,
  `MANDATORY_DOC_LDR` varchar(50) DEFAULT NULL,
  `RECEIVED_BY` varchar(50) DEFAULT NULL,
  `REQUIREMENT_CATEGORY` varchar(50) DEFAULT NULL,
  `MILESTONE` varchar(50) DEFAULT NULL,
  `INTERNALORCUSTOMER` varchar(20) DEFAULT NULL,
  `REQUIREMENT_DOC_TYPE` varchar(50) DEFAULT NULL,
  `LEDRD` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`REQ_MAPPING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `rider_details_table` (
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `RIDER_CODE` varchar(255) DEFAULT NULL,
  `RIDER_SA` varchar(200) DEFAULT NULL,
  `RIDER_RCD` date DEFAULT NULL,
  `RIDER_TERM` varchar(200) DEFAULT NULL,
  `RIDER_STATUS` varchar(200) DEFAULT NULL,
  `DECISION_SYSTEM` varchar(200) DEFAULT NULL,
  `DECISION_REASON_SYSTEM` varchar(200) DEFAULT NULL,
  `DECISION_ASSESSOR` varchar(200) DEFAULT NULL,
  `DECISION_REASON_ASSESSOR` varchar(200) DEFAULT NULL,
  `RIDER_CESSATION_DATE` date DEFAULT NULL,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `CREATED_ON` datetime DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `riderdetails` (
  `id` int NOT NULL AUTO_INCREMENT,
  `policyNumber` varchar(255) NOT NULL,
  `RiderCode` varchar(255) DEFAULT NULL,
  `RiderSA` int DEFAULT NULL,
  `RiderStatus` varchar(255) DEFAULT NULL,
  `RiderCessationdate` date DEFAULT NULL,
  `RiderRCD` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `roleids` (
  `id` int NOT NULL AUTO_INCREMENT,
  `policyNumber` varchar(255) NOT NULL,
  `AppointeeID` varchar(255) DEFAULT NULL,
  `BeneficiaryID` varchar(255) DEFAULT NULL,
  `ProposerID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `roles` (
  `role_description` text,
  `id` int DEFAULT NULL,
  `role_name` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `safe_city` (
  `city_Id` int NOT NULL AUTO_INCREMENT,
  `city_name` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`city_Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `safe_pincode` (
  `pincode_Id` int NOT NULL AUTO_INCREMENT,
  `pincode` int DEFAULT NULL,
  PRIMARY KEY (`pincode_Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `sampling_matrix_hist` (
  `HISTORY_ID` int DEFAULT NULL,
  `PIN_CODE` int DEFAULT NULL,
  `CITY` text,
  `SAMPLING_PERCENTAGE` text,
  `TOTAL_CLAIM_SAMPLED` text,
  `TOTAL_CLAIMS` text,
  `SERIAL_NO` int DEFAULT NULL,
  `CREATED_ON` datetime DEFAULT NULL,
  `CREATED_BY` text,
  `MODIFIED_ON` datetime DEFAULT NULL,
  `MODIFIED_BY` text,
  `STATUS` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `sms_script` (
  `SERIAL_NO` int DEFAULT NULL,
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `SMS_CODE` varchar(200) DEFAULT NULL,
  `SMS_TEXT` varchar(1000) DEFAULT NULL,
  `MOBILE_NUMBER` varchar(200) DEFAULT NULL,
  `TRIGGERED_BY` varchar(200) DEFAULT NULL,
  `TRIGGERED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `NOT_SEND_REASON` varchar(500) DEFAULT NULL,
  `SEND_FLAG` varchar(200) DEFAULT NULL,
  `CREATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `WHATSAPP_SEND_FLAG` varchar(200) DEFAULT NULL,
  `RETRIGGER` varchar(200) DEFAULT NULL,
  `ECAMP_DELIVERY_STATUS` varchar(200) DEFAULT NULL,
  `ECAMP_TRANS_ID` varchar(200) DEFAULT NULL,
  `SMS_CAMPAIGN_NAME` varchar(200) DEFAULT NULL,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_BY` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `states` (
  `name` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `status_history` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CLAIM_NUMBER` varchar(50) NOT NULL,
  `POLICY_NUMBER` varchar(50) NOT NULL,
  `MODIFIED_BY` varchar(100) NOT NULL,
  `MODIFIED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS` varchar(50) NOT NULL,
  `DECISION` varchar(255) DEFAULT NULL,
  `REMARKS` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `CREATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `system_assessor_remark` (
  `CLAIM_ID` varchar(255) DEFAULT NULL,
  `CASE` text,
  `UPDATE` text,
  `CASE_REASON` text,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(255) DEFAULT NULL,
  `MODIFIED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `system_remark` (
  `REM_ID` int NOT NULL AUTO_INCREMENT,
  `SL_NO` varchar(200) DEFAULT NULL,
  `REM_DATE` date DEFAULT NULL,
  `REMARKS` varchar(1000) DEFAULT NULL,
  `SCORE` varchar(200) DEFAULT NULL,
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `RESPONSE` varchar(200) DEFAULT NULL,
  `CREATEDON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` varchar(200) DEFAULT NULL,
  `MODIFIEDON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIEDBY` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`REM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `telecalling` (
  `TELECALLING_ID` int NOT NULL AUTO_INCREMENT,
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `REASON` varchar(200) DEFAULT NULL,
  `CALL_TO` varchar(200) DEFAULT NULL,
  `THE_DATE` date DEFAULT NULL,
  `OUTCOME` varchar(200) DEFAULT NULL,
  `CALL_BY` varchar(200) DEFAULT NULL,
  `DETAILS` varchar(4000) DEFAULT NULL,
  `CREATED_ON` date DEFAULT NULL,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`TELECALLING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `transaction_details` (
  `id` int NOT NULL AUTO_INCREMENT,
  `PolicyNumber` varchar(50) NOT NULL,
  `Date` date NOT NULL,
  `Code` varchar(20) NOT NULL,
  `Amount` decimal(15,2) NOT NULL,
  `Status` varchar(20) DEFAULT NULL,
  `Description` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `transactionapidetails` (
  `txnid` int NOT NULL AUTO_INCREMENT,
  `txnpolicyNumber` varchar(30) DEFAULT NULL,
  `txnDate` datetime DEFAULT NULL,
  `txnCode` varchar(20) DEFAULT NULL,
  `txnAmount` varchar(20) DEFAULT NULL,
  `txnStatus` varchar(20) DEFAULT NULL,
  `txnRemark` varchar(20) DEFAULT NULL,
  `txnDescription` text,
  `txnAction` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`txnid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `trap_score` (
  `CLAIM_ID` varchar(255) DEFAULT NULL,
  `TRAP_ID` int NOT NULL AUTO_INCREMENT,
  `TRAP_SCORE_DATE` date DEFAULT NULL,
  `ASSESSOR_NAME` varchar(255) DEFAULT NULL,
  `ASSESSOR_ID` varchar(255) DEFAULT NULL,
  `TRAP_REMARKS` varchar(10000) DEFAULT NULL,
  `TRAP_SCORE` double DEFAULT NULL,
  PRIMARY KEY (`TRAP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `trap_score_master` (
  `SEQ_NO` int DEFAULT NULL,
  `FIELD_NAME` text,
  `VALUE` text,
  `SCORE` int DEFAULT NULL,
  `REMARK` text,
  `CREATED_ON` datetime DEFAULT NULL,
  `CREATED_BY` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `uploadeddocuments` (
  `documentId` int NOT NULL AUTO_INCREMENT,
  `claimId` varchar(50) DEFAULT NULL,
  `fileName` varchar(100) DEFAULT NULL,
  `documentType` varchar(50) DEFAULT NULL,
  `alfrescoRepoId` varchar(100) DEFAULT NULL,
  `uploadedOn` datetime DEFAULT NULL,
  `createdBy` varchar(20) DEFAULT NULL,
  `AlfrescoFileId` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`documentId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `user_login_audit` (
  `ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(100) NOT NULL,
  `LOGIN_AT` datetime NOT NULL,
  `LOGOUT_AT` datetime DEFAULT NULL,
  `IP_ADDRESS` varchar(45) DEFAULT NULL,
  `USER_AGENT` varchar(255) DEFAULT NULL,
  `USER_ROLES` json DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_user_time` (`USERNAME`,`LOGIN_AT`),
  KEY `idx_login_time` (`LOGIN_AT`),
  KEY `idx_logout_time` (`LOGOUT_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `users` (
  `phoneNumber` text,
  `email` text,
  `id` int NOT NULL AUTO_INCREMENT,
  `username` text,
  `password` text,
  `roles` json DEFAULT NULL,
  `first_name` text,
  `last_name` text,
  `active` int DEFAULT NULL,
  `created_on` text,
  `created_by` text,
  `failed_attempts` int DEFAULT '0',
  `lockout_until` datetime DEFAULT NULL,
  `current_session_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `witness_details` (
  `POLICY_ID` varchar(200) DEFAULT NULL,
  `CLAIM_ID` varchar(200) DEFAULT NULL,
  `NAME` varchar(500) DEFAULT NULL,
  `REL_LA` varchar(200) DEFAULT NULL,
  `SEQUENCE` varchar(200) DEFAULT NULL,
  `CREATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `MODIFIED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(200) DEFAULT NULL,
  `CATEGORY` varchar(200) DEFAULT NULL,
  `ADDRESS_ID` varchar(200) DEFAULT NULL,
  `OTHER_RELATIONSHIP` varchar(200) DEFAULT NULL,
  `MILESTONE` varchar(100) DEFAULT NULL,
  `SIGNATURE` varchar(200) DEFAULT NULL,
  `INSTANCE_NO` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- @DOWN  ----------------------------------------------------------------------
-- WARNING: rolling back the baseline DROPS every table listed above and all
-- data in them. Intended only for tearing down a fresh/throwaway database.

DROP TABLE IF EXISTS `acuity_watchlist`;
DROP TABLE IF EXISTS `agent_repudiation_history`;
DROP TABLE IF EXISTS `agentdetails`;
DROP TABLE IF EXISTS `agentrepudiation`;
DROP TABLE IF EXISTS `attachment`;
DROP TABLE IF EXISTS `caps_add_activity_trail`;
DROP TABLE IF EXISTS `caps_add_assessor_pool_cases`;
DROP TABLE IF EXISTS `caps_add_contract_details`;
DROP TABLE IF EXISTS `caps_add_decision`;
DROP TABLE IF EXISTS `caps_add_decision_history`;
DROP TABLE IF EXISTS `caps_add_decision_master`;
DROP TABLE IF EXISTS `caps_add_details`;
DROP TABLE IF EXISTS `caps_add_details_history`;
DROP TABLE IF EXISTS `caps_add_exclusion_master`;
DROP TABLE IF EXISTS `caps_add_findings`;
DROP TABLE IF EXISTS `caps_add_iib_enquiry`;
DROP TABLE IF EXISTS `caps_add_krn_details`;
DROP TABLE IF EXISTS `caps_add_letter_details`;
DROP TABLE IF EXISTS `caps_add_life_assured_details`;
DROP TABLE IF EXISTS `caps_add_raw_data`;
DROP TABLE IF EXISTS `caps_add_requirement_master`;
DROP TABLE IF EXISTS `caps_add_rider_details`;
DROP TABLE IF EXISTS `caps_add_sms_details`;
DROP TABLE IF EXISTS `caps_add_sms_master`;
DROP TABLE IF EXISTS `caps_assessment_qustns_master`;
DROP TABLE IF EXISTS `caps_bre_requirement_master`;
DROP TABLE IF EXISTS `caps_eagle_rule_details`;
DROP TABLE IF EXISTS `caps_event_details`;
DROP TABLE IF EXISTS `caps_fraud_flags_mapping`;
DROP TABLE IF EXISTS `caps_fraud_master`;
DROP TABLE IF EXISTS `caps_new_terms_plan_master`;
DROP TABLE IF EXISTS `caps_other_insurance`;
DROP TABLE IF EXISTS `caps_past_illness_details`;
DROP TABLE IF EXISTS `caps_policy_bre`;
DROP TABLE IF EXISTS `caps_portfolio_master`;
DROP TABLE IF EXISTS `caps_priority_flags_mapping`;
DROP TABLE IF EXISTS `caps_priority_master`;
DROP TABLE IF EXISTS `caps_product_details`;
DROP TABLE IF EXISTS `caps_rider_details`;
DROP TABLE IF EXISTS `caps_rider_mapping_codes`;
DROP TABLE IF EXISTS `caps_transaction_bre`;
DROP TABLE IF EXISTS `case_reasons`;
DROP TABLE IF EXISTS `case_trigger`;
DROP TABLE IF EXISTS `cause_event`;
DROP TABLE IF EXISTS `cause_of_claim`;
DROP TABLE IF EXISTS `cause_of_claim_master`;
DROP TABLE IF EXISTS `claim_questions`;
DROP TABLE IF EXISTS `claim_sequence`;
DROP TABLE IF EXISTS `claimant_details`;
DROP TABLE IF EXISTS `claims`;
DROP TABLE IF EXISTS `clientdetails`;
DROP TABLE IF EXISTS `common_and_rider_details`;
DROP TABLE IF EXISTS `contact_details`;
DROP TABLE IF EXISTS `contractdetails`;
DROP TABLE IF EXISTS `countries`;
DROP TABLE IF EXISTS `decision_accessor`;
DROP TABLE IF EXISTS `decision_details`;
DROP TABLE IF EXISTS `decision_system`;
DROP TABLE IF EXISTS `decision_verification_and_summary`;
DROP TABLE IF EXISTS `doctor_details`;
DROP TABLE IF EXISTS `documentlist`;
DROP TABLE IF EXISTS `eagle_screen`;
DROP TABLE IF EXISTS `established_cause`;
DROP TABLE IF EXISTS `fraud_flags_mapping`;
DROP TABLE IF EXISTS `hospital_details`;
DROP TABLE IF EXISTS `iib_enquiry`;
DROP TABLE IF EXISTS `inbox`;
DROP TABLE IF EXISTS `income_details`;
DROP TABLE IF EXISTS `intimation_details`;
DROP TABLE IF EXISTS `lapsed_policies_master`;
DROP TABLE IF EXISTS `letters_and_emails`;
DROP TABLE IF EXISTS `life_assured_details`;
DROP TABLE IF EXISTS `parallel_policies`;
DROP TABLE IF EXISTS `payee_details`;
DROP TABLE IF EXISTS `place_of_death`;
DROP TABLE IF EXISTS `proof_details`;
DROP TABLE IF EXISTS `requirement_master`;
DROP TABLE IF EXISTS `requirement_table`;
DROP TABLE IF EXISTS `requirements`;
DROP TABLE IF EXISTS `rider_details_table`;
DROP TABLE IF EXISTS `riderdetails`;
DROP TABLE IF EXISTS `roleids`;
DROP TABLE IF EXISTS `roles`;
DROP TABLE IF EXISTS `safe_city`;
DROP TABLE IF EXISTS `safe_pincode`;
DROP TABLE IF EXISTS `sampling_matrix_hist`;
DROP TABLE IF EXISTS `sms_script`;
DROP TABLE IF EXISTS `states`;
DROP TABLE IF EXISTS `status_history`;
DROP TABLE IF EXISTS `system_assessor_remark`;
DROP TABLE IF EXISTS `system_remark`;
DROP TABLE IF EXISTS `telecalling`;
DROP TABLE IF EXISTS `transaction_details`;
DROP TABLE IF EXISTS `transactionapidetails`;
DROP TABLE IF EXISTS `trap_score`;
DROP TABLE IF EXISTS `trap_score_master`;
DROP TABLE IF EXISTS `uploadeddocuments`;
DROP TABLE IF EXISTS `user_login_audit`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `witness_details`;
