import { jsPDF } from 'jspdf'
import {
  MARGIN,
  FOOTER_H,
  C,
  COMPANY,
  setFill,
  setText,
  setDraw,
  formatPdfDate,
  addCalendarDays,
  loadLogoDataUrl,
  drawFooter,
  drawKpiChip,
  drawBrandedHeader,
  drawSectionCard,
  drawCertificationBlock,
} from './pdfBranding'

export const SCN_REPLY_MAX_DAYS = 15

const STANDARD_REQUIREMENTS = [
  'Duly signed claim form',
  'Policy certificate / schedule',
  'Government-issued photo ID of claimant / payee',
  'Address proof matching claim form',
  'Death certificate (attested copy, if applicable)',
  'Bank account proof (cancelled cheque or passbook)',
]

function buildRequirementList(findings = []) {
  const fromFindings = findings
    .filter((r) => r.findings || r.remarks || r.evidenceType)
    .map((r) => {
      const parts = [r.findings, r.remarks, r.evidenceType].filter(Boolean)
      return parts.join(' — ')
    })
  const merged = [...STANDARD_REQUIREMENTS]
  fromFindings.forEach((line) => {
    if (line && !merged.some((m) => m.toLowerCase() === line.toLowerCase())) {
      merged.push(line)
    }
  })
  return merged
}

function drawRequirementsList(doc, x, y, colWidth, requirements) {
  const numbered = requirements.map((req, i) => `${i + 1}. ${req}`)
  const body = numbered.join('\n')

  const section = {
    title: 'Documents / requirements to be submitted',
    rows: [{ label: 'Checklist', value: body }],
  }

  return drawSectionCard(doc, section, x, y, colWidth)
}

function drawReplyWindow(doc, x, y, colWidth, scnDate) {
  const boxH = 20
  setFill(doc, C.amberBg)
  setDraw(doc, [253, 230, 138])
  doc.roundedRect(x, y, colWidth, boxH, 2, 2, 'FD')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7.5)
  setText(doc, C.amber)
  doc.text('REPLY WINDOW', x + 4, y + 5.5)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  setText(doc, C.slate)
  const dueBy = addCalendarDays(scnDate, SCN_REPLY_MAX_DAYS)
  const notice = `The claimant / payee must respond with all listed requirements within ${SCN_REPLY_MAX_DAYS} calendar days from the SCN date (${formatPdfDate(scnDate)}). Reply due by ${dueBy}. Late replies may affect claim processing.`
  const lines = doc.splitTextToSize(notice, colWidth - 8)
  doc.text(lines, x + 4, y + 11)

  return y + boxH + 4
}

/**
 * Generate branded SCN (Show Cause Notice) PDF — matches DH claim summary styling.
 */
export async function downloadScnNoticePdf({
  caseId,
  policyNo,
  krn,
  scnDate,
  scnAging,
  finalDecision,
  remarks,
  findings = [],
  generatedAt = new Date(),
}) {
  const logoDataUrl = await loadLogoDataUrl()
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const contentWidth = pageWidth - MARGIN * 2
  const colGap = 6
  const colWidth = (contentWidth - colGap) / 2
  const leftX = MARGIN
  const rightX = MARGIN + colWidth + colGap

  setFill(doc, C.rowAlt)
  doc.rect(0, 0, pageWidth, pageHeight, 'F')

  let y = await drawBrandedHeader(doc, logoDataUrl, {
    title: 'Show Cause Notice',
    subtitle: `${COMPANY.product} · Advance Intelligence`,
    generatedAt,
    bannerText: 'INTERNAL USE ONLY — SHOW CAUSE NOTICE',
  })

  const chipW = (contentWidth - 9) / 4
  drawKpiChip(doc, MARGIN, y, chipW, 'Case ID', caseId, true)
  drawKpiChip(doc, MARGIN + chipW + 3, y, chipW, 'Policy Number', policyNo)
  drawKpiChip(doc, MARGIN + (chipW + 3) * 2, y, chipW, 'KRN', krn)
  drawKpiChip(doc, MARGIN + (chipW + 3) * 3, y, chipW, 'SCN Aging', scnAging != null ? `${scnAging} days` : '0 days')
  y += 17

  const scnSection = {
    title: 'SCN Details',
    rows: [
      { label: 'SCN Sent', value: 'Yes' },
      { label: 'SCN Date', value: formatPdfDate(scnDate) },
      { label: 'Reply Due By', value: addCalendarDays(scnDate, SCN_REPLY_MAX_DAYS) },
      { label: 'Final Decision', value: finalDecision },
    ],
  }

  const requirements = buildRequirementList(findings)
  let leftY = drawSectionCard(doc, scnSection, leftX, y, colWidth)
  let rightY = drawRequirementsList(doc, rightX, y, colWidth, requirements)

  y = Math.max(leftY, rightY)
  y = drawReplyWindow(doc, MARGIN, y, contentWidth, scnDate)

  if (remarks) {
    const remarksSection = {
      title: 'Assessor Remarks',
      rows: [{ label: 'Comments', value: String(remarks) }],
    }
    y = drawSectionCard(doc, remarksSection, MARGIN, y, contentWidth)
  }

  const certText = `This Show Cause Notice was automatically generated by ${COMPANY.name} ${COMPANY.product} and reflects case data at the time of export. For verification or queries, contact ${COMPANY.email} or ${COMPANY.phone}.`
  const certY = pageHeight - FOOTER_H - 19
  drawCertificationBlock(doc, Math.min(y, certY), contentWidth, certText)

  drawFooter(doc, generatedAt)

  const safeId = String(caseId || 'notice').replace(/[^\w.-]+/g, '_')
  doc.save(`DH-SCN-Case-${safeId}.pdf`)
}
