import { jsPDF } from 'jspdf'
import { buildCaseSummaryReport } from './caseSummaryText'
import {
  MARGIN,
  FOOTER_H,
  C,
  COMPANY,
  setFill,
  setDraw,
  setText,
  loadLogoDataUrl,
  drawFooter,
  drawKpiChip,
  drawBrandedHeader,
  drawSectionCard,
  drawCertificationBlock,
} from './pdfBranding'

function statusStyle(status) {
  const s = String(status || '').toLowerCase()
  if (s.includes('approv') || s.includes('payout completed')) return { bg: C.greenBg, fg: C.green }
  if (s.includes('reject') || s.includes('repudi')) return { bg: [254, 242, 242], fg: [153, 27, 27] }
  return { bg: C.amberBg, fg: C.amber }
}

/**
 * Download a premium branded single-page PDF case summary report.
 */
export async function downloadCaseSummaryPdf({ claim, demogs, generatedAt = new Date() }) {
  const report = buildCaseSummaryReport(claim, demogs)
  const claimId = String(report.claimId || 'claim').trim() || 'claim'

  if (!report.sections?.length) {
    throw new Error('No case summary content to download.')
  }

  const logoDataUrl = await loadLogoDataUrl()
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const contentWidth = pageWidth - MARGIN * 2
  const colGap = 6
  const colWidth = (contentWidth - colGap) / 2
  const leftX = MARGIN
  const rightX = MARGIN + colWidth + colGap

  setFill(doc, C.rowAlt)
  doc.rect(0, 0, pageWidth, pageHeight, 'F')

  let y = await drawBrandedHeader(doc, logoDataUrl, {
    title: 'Claim Case Summary',
    subtitle: COMPANY.product,
    generatedAt,
    bannerText: 'INTERNAL USE ONLY — CLAIM INTELLIGENCE REPORT',
  })

  const overview = report.sections.find((s) => s.title === 'Claim Overview')
  const statusVal = overview?.rows.find((r) => r.label === 'Workflow Status')?.value || claim?.status
  const daysVal = overview?.rows.find((r) => r.label === 'Days Open')?.value || claim?.daysOpen
  const chipW = (contentWidth - 9) / 4

  drawKpiChip(doc, MARGIN, y, chipW, 'Claim Number', report.claimId || claim?.claimId, true)
  drawKpiChip(doc, MARGIN + chipW + 3, y, chipW, 'Policy Number', report.policyId || claim?.policyId)

  const st = statusStyle(statusVal)
  const statusX = MARGIN + (chipW + 3) * 2
  setFill(doc, st.bg)
  setDraw(doc, C.border)
  doc.roundedRect(statusX, y, chipW, 14, 2, 2, 'FD')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(6)
  setText(doc, C.muted)
  doc.text('WORKFLOW STATUS', statusX + 3, y + 4.5)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  setText(doc, st.fg)
  const stLines = doc.splitTextToSize(String(statusVal || '—'), chipW - 6)
  doc.text(stLines[0], statusX + 3, y + 10.5)

  drawKpiChip(doc, MARGIN + (chipW + 3) * 3, y, chipW, 'Days Open', daysVal != null ? `${daysVal} days` : '—')
  y += 17

  const sections = report.sections.filter((s) => s.title !== 'Claim Overview')
  const splitAt = Math.ceil(sections.length / 2)
  const leftSections = sections.slice(0, splitAt)
  const rightSections = sections.slice(splitAt)

  let leftY = y
  leftSections.forEach((section) => {
    leftY = drawSectionCard(doc, section, leftX, leftY, colWidth)
  })

  let rightY = y
  rightSections.forEach((section) => {
    rightY = drawSectionCard(doc, section, rightX, rightY, colWidth)
  })

  y = Math.max(leftY, rightY) + 2

  const certH = 16
  const maxCertY = pageHeight - FOOTER_H - certH - 3
  if (y > maxCertY) y = maxCertY

  const certText = `This report was automatically generated by ${COMPANY.name} ${COMPANY.product} and reflects claim data at the time of export. For verification or queries, contact ${COMPANY.email} or ${COMPANY.phone}.`
  drawCertificationBlock(doc, y, contentWidth, certText)

  drawFooter(doc, generatedAt)

  doc.save(`DH-Claim-Summary-${claimId.replace(/[^\w.-]+/g, '_')}.pdf`)
}
